### ISSUE TITLE
how to use older version of mmdecetion

### ISSUE THREAD

**Issue by SmallingCar** [open-mmlab/mmdetection#10139]
I want to use version of 2.25.2 mmdetection,what should i do ?

**Comment by SmallingCar** [comment]
i have solved this problem

**Comment by jokulsarlon777** [comment]
how could you solve this problem?
I want to previous mmdectection model like 2.28.0 or 2.28.2
but I can't install mmcv-full

**Comment by VLadImirluren** [comment]
> I want to use version of 2.25.2 mmdetection,what should i do ?

I want to use a version of mmdet3d that need the mmcv-full version is <= 2.0.

How did you solve the problem of installing older version?

Could you please give me some advice.

I meet the problem is that
<img width="1097" alt="image" src="https://github.com/open-mmlab/mmdetection/assets/94054234/033427c6-5205-44c0-bc9a-5aad78bb9c61">

Thanks...
