### ISSUE TITLE
Any plans for centernet : objects as points?

### ISSUE THREAD

**Issue by Epiphqny** [open-mmlab/mmdetection#1017]
An effective model for one-stage object detection. https://github.com/xingyizhou/CenterNet

**Comment by bhack** [comment]
Check also https://github.com/open-mmlab/mmdetection/issues/55#issuecomment-511788071

**Comment by Ridhwanluthra** [comment]
@Epiphqny I am currently working on integrating that. you can follow the progress at github.com/ridhwanluthra/mmdetection
I will be submitting a pull request soon

**Comment by Epiphqny** [comment]
> @Epiphqny I am currently working on integrating that. you can follow the progress at [my fork ](https://github.com/Ridhwanluthra/mmdetection)for now I will be submitting a pull request soon

I will follow it, thank you very much!

**Comment by lizhe960118** [comment]
can not test use this code

**Comment by Epiphqny** [comment]
> @Epiphqny I am currently working on integrating that. you can follow the progress at [my fork ](https://github.com/Ridhwanluthra/mmdetection)for now I will be submitting a pull request soon

I used your code but have a question, if the hourglass network has been pretrained or not ?

**Comment by Epiphqny** [comment]
> can not test use this code

same problem@Ridhwanluthra

**Comment by mathmanu** [comment]
@Ridhwanluthra I was excited to hear your proposed PR for ObjectAsPointsCenterNet, because I believe it is conceptually the simplest Object Detector. However, I looked through your implementation [https://github.com/Ridhwanluthra/mmdetection/tree/centernet_pr](here)
And got some questions:
1. CenterNet is derived from TwoStageDetector - shouldn't it use SingleStageDetector instead?
2. Several aspects that are specific to centernet are actually implemented in custom dataset - with flags to switch between with_ctdet mode and otherwise. Is there a better/structured way of doing it?
Thanks,

**Comment by bhack** [comment]
There Is also FreeAnchor a new Neurips 19 work:

https://github.com/zhangxiaosong18/FreeAnchor

**Comment by bhack** [comment]
The PR Is at https://github.com/zhangxiaosong18/FreeAnchor

**Comment by mathmanu** [comment]
@bhack  Reading through the paper, I realized it's really FreeAnchor (choose an anchor by training) and not an Anchor-Free (no anchor) method. I was looking for an Anchor-Free method.
However, your method has excellent results and the PR looks clean.  Keep up the good work!

**Comment by bhack** [comment]
Yes they are based on two different concepts of anchor "Freedom".

**Comment by mathmanu** [comment]
@Ridhwanluthra, I can see that in your pr_submission, you are not using custom dataset any more. Thanks for taking care of this.

**Comment by biyuruofeng** [comment]
Hello,what's the progress of centernet?

**Comment by ZwwWayne** [comment]
Supported through https://github.com/open-mmlab/mmdetection/pull/4602
