### ISSUE TITLE
Why is it slower to use 8 GPUs than 4 GPUs

### ISSUE THREAD

**Issue by ElegantLin** [open-mmlab/mmdetection#1117]
I used Synchronized BN in my backbone. The time using 8 GPUs is almost twice as much as that of 4 GPUs. Is it normal?

Thanks.

**Comment by hellock** [comment]
Usually the time cost of each iteration is comparable. 4 GPU may be slightly faster than 8 GPU.

**Comment by ElegantLin** [comment]
Thanks for your reply. But I am puzzled why 8 is slower than that of 4. Is this the problem of the distributed training of PyTorch 1.1.0 itself?

**Comment by hellock** [comment]
Not sure about your case, but I do not think it is a PyTorch issue since it works fine for us on various environments. The communication cost is slightly higher for 8 GPU training compared with 4 GPU training. Although the time cost of each iteration is comparable, the total iterations of 8 GPU training is only half of that of 4 GPU training, thus the total training time is nearly half.

**Comment by ElegantLin** [comment]
IC 

THX~ :)
