### ISSUE TITLE
Can the cleanroom design of yolov8 be merged into mmdet?

### ISSUE THREAD

**Issue by ryan-minato** [open-mmlab/mmdetection#11642]
I believe you have stored the yolo series in a separate repo due to GPL contamination issues. 
I would like to know will you merge it into this Apache-2.0 licensed repository if I re-implement yolov8 without reading the yolov8 source code, based on an analysis report from another person that does not involve ultralytics's source code.

If possible, what kind of standards should I adhere to in order to prevent any potential licensing issues?

**Comment by azad96** [comment]
Hi @ryan-minato, I am trying to use yolov8 inside mmdetection. Since its config files are not included in this repo but in mmyolo, I copied the config folder of yolov8 from mmyolo to mmdetection. However, it does not seem like it's compatible. It raises errors when running the demo script. Did you manage to use yolov8 in mmdetection?
