### ISSUE TITLE
GPU Memory grows while training HTC model with my own dataset.

### ISSUE THREAD

**Issue by michaelyyq** [open-mmlab/mmdetection#1185]
config:
I use the config file 'htc_without_semantic_r50_fpn_1x.py' and modify it a little like change the mstrain  scale range and add ga_rpn head.
question:
when I train the model, once trained one or two epoch, the gpu will be out of memory and stop with no error raised. I don't figure out why it  always happend.

**Comment by hellock** [comment]
Just because your GPU memory is insufficient to meet the requirement of the largest image batch.

**Comment by michaelyyq** [comment]
You're right. The highest scale input images cause the overflow.  But what confused me is that multi-scale training didn't randomly sample from the range of multi-scales but gradually increase.

**Comment by hellock** [comment]
As stated in the [documentation](https://github.com/open-mmlab/mmdetection/blob/master/MODEL_ZOO.md#common-settings), the memory displayed in the log is obtained with `torch.cuda.max_memory_allocated()`. The number is the maximum allocated memory since the training starts, so it always gets increasing or remains the same.

**Comment by michaelyyq** [comment]
Awesome! That's what makes me clear.Thanks a lot.
