### ISSUE TITLE
what's the meaning of results from maskrcnn

### ISSUE THREAD

**Issue by Mrqianduoduo** [open-mmlab/mmdetection#1208]
when I trained a model, I test it. But I don't what to use the API to show results, I want to know the points of masks. However, i don't understand the meaning such as 
 {'size': [800, 800], 'counts': b'fXQ79eh06J5L4L5L5I7K4L4L3M4L6J2N4L7I2N4NOO2L201O02O0O00001O0000002M3N1M200O10OO2N1F:10N1017H2O001O1O2N2N4L1O001O0000FaYOTN_f0b1fYOUNN8]f0b1jYO^NWf0`1iYOaNZf0Q23N5K4K2M6K2\\NfXO^1bg0L6J9F?A7FZVh:'}
can any body help me, thank you.

**Comment by hellock** [comment]
It is RLE string. You may refer to the [coco api](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/mask.py) for more information.

**Comment by RohitMidha23** [comment]
@hellock is it a RLE Encoded mask? 
Also in another issue it says `'It seems that the method of writing the results in test is not the same as the standard coco format, because it can still run normally when reading the training dataSet directly.'` so how do we covert the result string to either a `binary mask` of `np.bool` type or as a mask accepted by `_mask` from `pycocotools`? 

Any help on the same would be appreciated!

**Comment by TreezzZ** [comment]
> @hellock is it a RLE Encoded mask?
> Also in another issue it says `'It seems that the method of writing the results in test is not the same as the standard coco format, because it can still run normally when reading the training dataSet directly.'` so how do we covert the result string to either a `binary mask` of `np.bool` type or as a mask accepted by `_mask` from `pycocotools`?
> 
> Any help on the same would be appreciated!

Have you solved it? I have the same problem. :(
