### ISSUE TITLE
How to test my own imges on multi GPU with my trained model?

### ISSUE THREAD

**Issue by hitlxm** [open-mmlab/mmdetection#128]

**Comment by hitlxm** [comment]
Thank for your reply! Can i use this code  for testing images https://github.com/open-mmlab/mmdetection#test-images on MulGPUs?  because  the images i wanna to test is obtained from videos, i dont wanna to save it,   @hellock

**Comment by hellock** [comment]
Then you can write your own video dataset instead of using `CustomDataset`.
Another approach is to implement multi-gpu testing for your case, which is not very straight forward.
[Here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/parallel_test.py) is a reference of how multi-gpu testing works.
