### ISSUE TITLE
Is there any way to visualize the feature maps?

### ISSUE THREAD

**Issue by Flawless1202** [open-mmlab/mmdetection#140]
I want to visualize some of the feature maps when training,  can the hook api work? And is there any documents for the hook api? Thanks a lot.

**Comment by hellock** [comment]
The high-level hooking apis provided by `mmcv.runner` can only be invoked before/after an iteration/epoch. If you want to visualize the intermediate feature maps instead of final outputs, you may need to modify the forward method to return the feature map, and then use the hooking apis in `mmcv.runner`. Or you can just use PyTorch's built-in low-level hooks, see [here](https://pytorch.org/docs/stable/nn.html?highlight=hook#torch.nn.Module.register_forward_hook) for details.
