### ISSUE TITLE
Develop build option

### ISSUE THREAD

**Issue by thangvubk** [open-mmlab/mmdetection#146]
Thank you for sharing!
I think that the code is under rapid development. It is nice if it has a develop build option using soft-link so users do not have to rebuild after making some modifications.

**Comment by hellock** [comment]
You can just run `pip install -e .` or `python setup.py develop` to install it with a soft link.

Since `mmcv.__version__` will record the git commit hash and be saved in checkpoints, it may be a good choice to run `python setup.py install` after each update. It's up to users to adopt the develop mode or not.

**Comment by thangvubk** [comment]
Thank you for your helpful information!
