### ISSUE TITLE
questions on cuda device

### ISSUE THREAD

**Issue by vincentwei0919** [open-mmlab/mmdetection#1560]
hi, I have trained a model and tried to predict on different gpu id different from training(eg: training on gpu1 and inference on gpu2). Then I found that when I use CUDA_VISIBLE_DEVICES to specify devices, all seemed work ok. But when I use parameters like "cuda(2)" to specify a device, it always 
report error like below:
![image](https://user-images.githubusercontent.com/24283259/67087676-fb6c0800-f1d5-11e9-9037-5f01eda1f287.png)
I find the model have been loaded on the specified gpu but some computing is working on gpu 0, which confused me a lot. After print some mid result, I find the quention is from the file below.

https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/anchor_heads/anchor_head.py

I use a source code published about two month ago. I find a change on line 255. which is added like 
"device=cls_scores[0].device", this parameter is also put in their following lines. 
the code I used now does not contain this line and after I added that , a cuda memory error happened :
![image](https://user-images.githubusercontent.com/24283259/67088069-d330d900-f1d6-11e9-92fa-9493e9cffb7a.png)

I wonder how that happened (model on gpu2 and some computing on gpu 0)? shall I use the new recent code to retrained my data? or any advices on how to fix this?
thanks a lot!

**Comment by ZwwWayne** [comment]
Hi @vincentwei0919 ，

This might because the model you saved and loaded was consist of GPU Tensor and has a different GPU ID, you may try to convert it to a CPU model first and then load it for inference.

If this bug is not solved, you could try the newest code to retrain on your data.

What is more, we would appreciate it if you could use the “Error report” issue template as indicated in https://github.com/open-mmlab/mmdetection/blob/master/.github/ISSUE_TEMPLATE/error-report.md
