### ISSUE TITLE
Why R-FCN branch closed 

### ISSUE THREAD

**Issue by haikuoyao** [open-mmlab/mmdetection#1576]
Hi  @yhcao6 

I saw a branch of R-FCN 

https://github.com/open-mmlab/mmdetection/pull/757/files
Why was it closed?
Can I  still use it?

Thanks.

**Comment by yhcao6** [comment]
Of course you can use, the performance on VOC is normal, but there are still some problems on coco.

**Comment by haikuoyao** [comment]
Thanks a lot. @yhcao6 
It's a really brilliant work and is what I'm looking for.
Cuz I'd like a much faster network than faster-rcnn.
Will try it today.

**Comment by TyroneLi** [comment]
> Of course you can use, the performance on VOC is normal, but there are still some problems on coco.

I wait for modifying RFCN for some time, but it was just been removed and it seems nobody try to modify.Could you fix this and merge it into mmdet as soon as possible?Because when I use original mmdet which was support rfcn, I could only train with one gpu and the loss was really easy to suck into nan.

**Comment by haikuoyao** [comment]
yeah. If has a trained coco model, it would be perfect.
(I might ask too much)
