### ISSUE TITLE
A Safety 'issue' at HK

### ISSUE THREAD

**Issue by FrankXinqi** [open-mmlab/mmdetection#1661]
Hi, all excellent researchers from mmlab, CUHK. 

Regarding the serious situation at HongKong SAR, are you guys safe?

Kindly greeting from a user of mmdetection...... ^^

**Comment by chrisjuniorli** [comment]
A very good issue

**Comment by hellock** [comment]
Thanks for your kind consideration! We have been safe in Shenzhen since yesterday.

**Comment by mr921112** [comment]
You can come to Shanghai, Beijing and Shenzhen to see it. It is very safe. No matter how many nights you go home, you don't have to worry about it. Because Chinese people like to live and work in peace, many people in Hong Kong are not Hong Kong people. They will only eventually drag Hong Kong into a second- and third-tier city in China.
