### ISSUE TITLE
nms错误

### ISSUE THREAD

**Issue by as754770178** [open-mmlab/mmdetection#1667]
我的代码每次运行到`nms_wrapper.py`文件中
```
    if dets_th.shape[0] == 0:
        inds = dets_th.new_zeros(0, dtype=torch.long)
    else:
        if dets_th.is_cuda:
            inds = nms_cuda.nms(dets_th, iou_thr)
        else:
            inds = nms_cpu.nms(dets_th, iou_thr)
```
都会崩溃：
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by ZwwWayne** [comment]
This might because the environment you are using now is different from that for compiling the code.
Directly Google/Baidu the bug message `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)` could help you, e.g., you could find this [blog](https://blog.csdn.net/leogo17/article/details/80928451) through Googling the message.

**Comment by hellock** [comment]
Please use English or English&Chinese for issues.
