### ISSUE TITLE
Don't understand img_scale=(1333, 800)

### ISSUE THREAD

**Issue by Hellcat1005** [open-mmlab/mmdetection#1736]
I am studying cascade_rcnn_x101_64x4d_fpn_1x. I think images will be resized to some shapes which are smaller than 1333 x 800, like 1333 x 750 or 1000 x 800. And then pad them to be multiple to some number (such as 32). After that, I think their shapes are not the same? So how to put them into a network and train with different input shapes?  I didn't find any code to make them the same shape.

**Comment by chuong98** [comment]
Due to different image size, we divide the images into two group: one with H>W, and another with H<W. Then, group 1 is resize to have H=800, and stack together along H dimension. Similarly, group 2 is resized to have W=1333, and stack together along W dimension. By doing so, you can preserve the H:W ratio of original images.

**Comment by hellock** [comment]
@Hellcat1005 Images in the same GPU are padded to the maximum size of these images.

@chuong98 Mostly correct, but group 1 is not necessarily resized to H=800 and group 2 to W=1333, they are just grouped by aspect ratios <1 and >1.
