### ISSUE TITLE
Questions about Libra R-CNN

### ISSUE THREAD

**Issue by c1aris** [open-mmlab/mmdetection#2069]
Hi! I noticed that compared with standard Faster R-CNN, Libra R-CNN uses a different sampling strategy for RPN as follows:

```
rpn=dict(
     assigner=dict(
          type='MaxIoUAssigner',
          pos_iou_thr=0.7,
          neg_iou_thr=0.3,
          min_pos_iou=0.3,
          ignore_iof_thr=-1),
    sampler=dict(
          type='RandomSampler',
          num=256,
          pos_fraction=0.5,
          neg_pos_ub=5,  # instead of -1
          add_gt_as_proposals=False),
     allowed_border=-1,  # instead of 0
     pos_weight=-1,
     debug=False)
```

According to my understanding, `neg_pos_ub` is the max ratio of num_neg_samples / num_pos_samples, and setting `allowed_border=-1` means keeping all the anchors even if part of which is outside the image. Do I misunderstand these two params?

Besides, it seems that the Libra R-CNN paper didn't mention the detailed sampling strategy for RPN. Is the config above the so-called "Libra RPN" in Table 3 in the paper?

<img width="449" alt="截屏2020-02-0901 39 21" src="https://user-images.githubusercontent.com/22849092/74089538-00362e00-4add-11ea-8043-92136ac7434b.png">

Thank you!

**Comment by OceanPang** [comment]
Hi, thanks for your attention. 

The shared Libra R-CNN config only adopts the IoU-balanced sampling in the second stage, not the RPN. You can directly modify the configs of the second stage to the first one and get the config of Libra RPN. 

We do not use the sampling strategy to the second stage because in the end-to-end training manner, the improvements on the recall of RPN may not influence the final AP. This conclusion has been verified by lots of literature.

Contact us if you still have some questions.

**Comment by c1aris** [comment]
Thank you for your reply!

Since IoU-balanced sampling is unnecessary and not used in the first stage, why not use the same config of RPN sampler from Faster R-CNN? Is there any trick to set `neg_pos_ub=5 (instead of -1)` and `allowed_border=-1 (instead of 0)`?

**Comment by OceanPang** [comment]
The `neg_pos_ub` and `allowed_border` won't influence the AP results, but the two terms indeed could improve the recall of RPN. The influences are trivial. 
You can directly focus on the setting of the second stage to understand the implementation of IoU-balanced Samling.

**Comment by c1aris** [comment]
I see, thank you so much!
