### ISSUE TITLE
Can I modify the IoU threshold of the test mode?

### ISSUE THREAD

**Issue by JamesQFreeman** [open-mmlab/mmdetection#2176]
It seems whatever change I made to the mmdetection/config/xx.py, the test results are always 0.5:0.95 , 0.5 and 0.75?
![image](https://user-images.githubusercontent.com/15217863/75605460-fc1a9080-5b1d-11ea-842a-ea9049bec4ab.png)

**Comment by hellock** [comment]
The `iou_thr` in your snapshot is the threshold used for NMS, it has nothing to do with the evaluation IoU threshold. If you are using the COCO dataset, `0.5:0.95` is the standard COCO-style evaluation, which is implemented by the [official evaluation code](https://github.com/cocodataset/cocoapi/tree/master/PythonAPI/pycocotools).

**Comment by Tunaaaaa** [comment]
@hellock So if I want to modify the IoU threshold of the test mode, for example, I want to know the recall and precision under one specific threshold, I could only write a new code from begining? Or is there any other tool can help doing this? Thank you very much.

**Comment by Ekta246** [comment]
Can anybody help me with one doubt?
I am trying to implement object detection task. 
So I have a dataset with .json annotation files for labels. Each image has only 1 object under 1 class. Can anyone suggest me any evaluation technique. I am unable to implement COCO evaluation on my dataset since I don't understand how do I use the coco_api on my style of dataset.

**Comment by Chen-Song** [comment]
> @hellock So if I want to modify the IoU threshold of the test mode, for example, I want to know the recall and precision under one specific threshold, I could only write a new code from begining? Or is there any other tool can help doing this? Thank you very much.

Hi, have you konwn to change where?
