### ISSUE TITLE
BBoxHead missing conv init

### ISSUE THREAD

**Issue by thangvubk** [open-mmlab/mmdetection#218]
ConvFCBBoxHead has [FC inits only](https://github.com/open-mmlab/mmdetection/blob/1b9f9b8866a53c695f906e644952d13618f10b95/mmdet/models/bbox_heads/convfc_bbox_head.py#L123) while detectron has both FC and conv initialized.

**Comment by hellock** [comment]
This is indeed misleading since we explicitly initialize fc layers but ignore conv layers. We use `ConvModule` in ConvFCBBoxHead, and `ConvModule` is implicitly [initialized](https://github.com/open-mmlab/mmdetection/blob/1b9f9b8866/mmdet/models/utils/conv_module.py#L64) with `kaiming_init` by default.

**Comment by hellock** [comment]
> Thanks for your info. I think implicit points should have a comment.

Totally agree. It will be updated.
