### ISSUE TITLE
reppoints_moment_x101_dcn_fpn_2x_mt，load pretrained model error

### ISSUE THREAD

**Issue by 237014845** [open-mmlab/mmdetection#2215]
I loaded the pretraining model of reppoints_moment_x101_dcn_fpn_2x_mt.py to train my dataset. Why can't I train DCN without type= 'DCN' in config, and can't I load DCN part of the pretrained model with type= 'DCN'

**Comment by ZwwWayne** [comment]
Hi @237014845 ,
Thanks for your bug report, this is because a recent PR that refactors the DCN module, but I forget to change the configs consistently in the RepPoints configs.
To quick fix the bug, you need to change the [dcn config](https://github.com/open-mmlab/mmdetection/blob/master/configs/reppoints/reppoints_moment_r101_dcn_fpn_2x_mt.py#L15)  as this [line](https://github.com/open-mmlab/mmdetection/blob/master/configs/dcn/mask_rcnn_dconv_c3-c5_r50_fpn_1x.py#L12). 
We will also create a PR to fix it ASAP.

**Comment by 237014845** [comment]
@ZwwWayne thank you for your reply!

**Comment by 237014845** [comment]
@ZwwWayne 我按照您被你所说的做了，但是仍然出现错误，如下：unexpected key in source state_dict: backbone.layer2.0.conv2_offset.weight, backbone.layer2.0.conv2_offset.bias, backbone.layer2.1.conv2_offset.weight, backbone.layer2.1.conv2_offset.bias, backbone.layer2.2.conv2_offset.weight, backbone.layer2.2.conv2_offset.bias, backbone.layer2.3.conv2_offset.weight, backbone.layer2.3.conv2_offset.bias, backbone.layer3.0.conv2_offset.weight, backbone.layer3.0.conv2_offset.bias, backbone.layer3.1.conv2_offset.weight, backbone.layer3.1.conv2_offset.bias, backbone.layer3.2.conv2_offset.weight, backbone.layer3.2.conv2_offset.bias, backbone.layer3.3.conv2_offset.weight, backbone.layer3.3.conv2_offset.bias, backbone.layer3.4.conv2_offset.weight, backbone.layer3.4.conv2_offset.bias, backbone.layer3.5.conv2_offset.weight, backbone.layer3.5.conv2_offset.bias, backbone.layer3.6.conv2_offset.weight, backbone.layer3.6.conv2_offset.bias, backbone.layer3.7.conv2_offset.weight, backbone.layer3.7.conv2_offset.bias, backbone.layer3.8.conv2_offset.weight, backbone.layer3.8.conv2_offset.bias, backbone.layer3.9.conv2_offset.weight, backbone.layer3.9.conv2_offset.bias, backbone.layer3.10.conv2_offset.weight, backbone.layer3.10.conv2_offset.bias, backbone.layer3.11.conv2_offset.weight, backbone.layer3.11.conv2_offset.bias, backbone.layer3.12.conv2_offset.weight, backbone.layer3.12.conv2_offset.bias, backbone.layer3.13.conv2_offset.weight, backbone.layer3.13.conv2_offset.bias, backbone.layer3.14.conv2_offset.weight, backbone.layer3.14.conv2_offset.bias, backbone.layer3.15.conv2_offset.weight, backbone.layer3.15.conv2_offset.bias, backbone.layer3.16.conv2_offset.weight, backbone.layer3.16.conv2_offset.bias, backbone.layer3.17.conv2_offset.weight, backbone.layer3.17.conv2_offset.bias, backbone.layer3.18.conv2_offset.weight, backbone.layer3.18.conv2_offset.bias, backbone.layer3.19.conv2_offset.weight, backbone.layer3.19.conv2_offset.bias, backbone.layer3.20.conv2_offset.weight, backbone.layer3.20.conv2_offset.bias, backbone.layer3.21.conv2_offset.weight, backbone.layer3.21.conv2_offset.bias, backbone.layer3.22.conv2_offset.weight, backbone.layer3.22.conv2_offset.bias, backbone.layer4.0.conv2_offset.weight, backbone.layer4.0.conv2_offset.bias, backbone.layer4.1.conv2_offset.weight, backbone.layer4.1.conv2_offset.bias, backbone.layer4.2.conv2_offset.weight, backbone.layer4.2.conv2_offset.bias

**Comment by 237014845** [comment]
@ZwwWayne I did what you were told, but still got errors, as follows: unexpected key in source state_dict: backbone.layer2.0.conv2_offset.weight, backbone.layer2.0.conv2_offset.bias, backbone.layer2.1. conv2_offset.weight, backbone.layer2.1.conv2_offset.bias, backbone.layer2.2.conv2_offset.weight, backbone.layer2.2.conv2_offset.bias, backbone.layer2.3.conv2_offset.weight, backbone.layer2.3. conv2_offset.bias, backbone.layer3.0.conv2_offset.weight, backbone.layer3.0.conv2_offset.bias, backbone.layer3.1.conv2_offset.weight, backbone.layer3.1.conv2_offset.bias, backbone.layer3.2. conv2_offset.weight, backbone.layer3.2.conv2_offset.bias, backbone.layer3.3.conv2_offset.weight, backbone.layer3.3.conv2_offset.bias, backbone.layer3.4.conv2_offset.weight, backbone.layer3.4. conv2_offset.bias, backbone.layer3.5.conv2_offset.weight, backbone.layer3.5.conv2_offset.bias, backbone.layer3.6.conv2_offset.weight, backbone.layer3.6.conv2_offset.bias, backbone.layer3.7. conv2_offset.weight, backbone.layer 3. 7.conv2_offset.bias, backbone.layer3.8.conv2_offset.weight, backbone.layer3.8.conv2_offset.bias, backbone.layer3.9.conv2_offset.weight, backbone.layer3.9.conv2_offset.bias, backbone.layer 3. 10.conv2_offset.weight, backbone.layer3.10.conv2_offset.bias, backbone.layer3.11.conv2_offset.weight, backbone.layer3.11.conv2_offset.bias, backbone.layer3.12.conv2_offset.weight, backbone.layer3. 12.conv2_offset.bias, backbone.layer3.13.conv2_offset.weight, backbone.layer3.13.conv2_offset.bias, backbone.layer3.14.conv2_offset.weight, backbone.layer3.14.conv2_offset.bias, backbone.layer3. 15.conv2_offset.weight, backbone.layer3.15.conv2_offset.bias, backbone.layer3.16.conv2_offset.weight, backbone.layer3.16.conv2_offset.bias, backbone.layer3.17.conv2_offset.weight, backbone.layer3. 17.conv2_offset.bias, backbone.layer3.18.conv2_offset.weight, backbone.layer3.18.conv2_offset.bias, backbone.layer3.19.conv2_offset.weight, backbone.layer3.19.conv2_offset.bias, backbone.layer3. 20.conv2_offset.weight, backbon e.layer3.20.conv2_offset.bias, backbone.layer3.21.conv2_offset.weight, backbone.layer3.21.conv2_offset.bias, backbone.layer3.22.conv2_offset.weight, backbone.layer3.22.conv2_offset.bias, backbone.layer4.0.conv2_offset.weight, backbone.layer4.0.conv2_offset.bias, backbone.layer4.1.conv2_offset.weight, backbone.layer4.1.conv2_offset.bias, backbone.layer4.2.conv2_offset.weight, backbone.layer4.2.conv2_offset.bias

**Comment by shraddhaamohan** [comment]
@ZwwWayne @237014845 I get a similar error while trying to load pretrained weights for htc_dconv_c3-c5_mstrain_x101_64x4d_fpn_20e.py I'm assuming its due to the recent changes with the implementation of DCN. Did you have any luck fixing it?

This is what i get:
The model and loaded state dict do not match exactly
unexpected key in source state_dict: backbone.layer2.0.conv2_offset.weight, backbone.layer2.0.conv2_offset.bias, backbone.layer2.1.conv2_of
fset.weight, backbone.layer2.1.conv2_offset.bias, backbone.layer2.2.conv2_offset.weight, backbone.layer2.2.conv2_offset.bias, backbone.laye
r2.3.conv2_offset.weight, backbone.layer2.3.conv2_offset.bias, backbone.layer3.0.conv2_offset.weight, backbone.layer3.0.conv2_offset.bias, 
backbone.layer3.1.conv2_offset.weight, backbone.layer3.1.conv2_offset.bias, backbone.layer3.2.conv2_offset.weight, backbone.layer3.2.conv2_
offset.bias, backbone.layer3.3.conv2_offset.weight, backbone.layer3.3.conv2_offset.bias, backbone.layer3.4.conv2_offset.weight, backbone.la
yer3.4.conv2_offset.bias, backbone.layer3.5.conv2_offset.weight, backbone.layer3.5.conv2_offset.bias, backbone.layer3.6.conv2_offset.weight
, backbone.layer3.6.conv2_offset.bias, backbone.layer3.7.conv2_offset.weight, backbone.layer3.7.conv2_offset.bias, backbone.layer3.8.conv2_
offset.weight, backbone.layer3.8.conv2_offset.bias, backbone.layer3.9.conv2_offset.weight, backbone.layer3.9.conv2_offset.bias, backbone.la
yer3.10.conv2_offset.weight, backbone.layer3.10.conv2_offset.bias, backbone.layer3.11.conv2_offset.weight, backbone.layer3.11.conv2_offset.
bias, backbone.layer3.12.conv2_offset.weight, backbone.layer3.12.conv2_offset.bias, backbone.layer3.13.conv2_offset.weight, backbone.layer3
.13.conv2_offset.bias, backbone.layer3.14.conv2_offset.weight, backbone.layer3.14.conv2_offset.bias, backbone.layer3.15.conv2_offset.weight
, backbone.layer3.15.conv2_offset.bias, backbone.layer3.16.conv2_offset.weight, backbone.layer3.16.conv2_offset.bias, backbone.layer3.17.co
nv2_offset.weight, backbone.layer3.17.conv2_offset.bias, backbone.layer3.18.conv2_offset.weight, backbone.layer3.18.conv2_offset.bias, back
bone.layer3.19.conv2_offset.weight, backbone.layer3.19.conv2_offset.bias, backbone.layer3.20.conv2_offset.weight, backbone.layer3.20.conv2_
offset.bias, backbone.layer3.21.conv2_offset.weight, backbone.layer3.21.conv2_offset.bias, backbone.layer3.22.conv2_offset.weight, backbone
.layer3.22.conv2_offset.bias, backbone.layer4.0.conv2_offset.weight, backbone.layer4.0.conv2_offset.bias, backbone.layer4.1.conv2_offset.we
ight, backbone.layer4.1.conv2_offset.bias, backbone.layer4.2.conv2_offset.weight, backbone.layer4.2.conv2_offset.bias

**Comment by ZwwWayne** [comment]
Hi @237014845 & @shraddhaamohan ,
The unexpected key shows up because their names are changed in the new DCN module and they are loaded in another name. Therefore, as long as the necessary key is not missing, i.e., there is no warning about missing keys, the checkpoint is loaded successfully and the results should be the same.

We will release all the new models after the BC-breaking refactoring, in about two weeks. After then those warning will be fixed.

**Comment by shraddhaamohan** [comment]
@ZwwWayne thanks for that clarification, just ran inference and can comfirm it works just the same. Thanks a lot!

**Comment by ZwwWayne** [comment]
Hi @shraddhaamohan ,
Thanks for your report. Feel free to reopen this issue if the performance of the pre-trained models does not match.
