### ISSUE TITLE
any plans for visualization?

### ISSUE THREAD

**Issue by bigpo** [open-mmlab/mmdetection#228]
thanks for your incredible work! is there any plan for adding visualization tools such as tensorboardX?

**Comment by thangvubk** [comment]
To my knowledge, tensorboardX visualization is implemented. You just uncomment this [line](https://github.com/open-mmlab/mmdetection/blob/1b9f9b8866a53c695f906e644952d13618f10b95/configs/faster_rcnn_r50_fpn_1x.py#L146) in the config file. 

@hellock Since tensorboardX is helpful, using tensorboardX as default should be a nice idea

**Comment by bigpo** [comment]
my bad, i missed this line, thanks! @thangvubk
