### ISSUE TITLE
How to use CosineAnnealingLR?

### ISSUE THREAD

**Issue by kalayan** [open-mmlab/mmdetection#2286]
I found that mmdetect has "cosine" learning policy, it make lt look like 
![image](https://user-images.githubusercontent.com/13598493/76913124-11026c80-68f1-11ea-8ef2-ccc91d536f3d.png)

But I want to use CosineAnnealingLR, lr should lokk like
![image](https://user-images.githubusercontent.com/13598493/76913162-29728700-68f1-11ea-94bf-cd74a0671121.png)

How to use CosineAnnealingLR in mmdetection? Thanks a lot!

**Comment by ZwwWayne** [comment]
Hi @kalayan ,
MMDetection depends on the hooks implemented in [MMCV](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/lr_updater.py) to control the learning rate. Cyclic LR seems to be not implemented for now because we do not usually use cyclic LR in current standard practice. Therefore, you might need to implement it by yourself.

**Comment by kalayan** [comment]
> Hi @kalayan ,
> MMDetection depends on the hooks implemented in [MMCV](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/lr_updater.py) to control the learning rate. Cyclic LR seems to be not implemented for now because we do not usually use cyclic LR in current standard practice. Therefore, you might need to implement it by yourself.

Thanks!
