### ISSUE TITLE
 target_stds value in rpn_head  and bbox_head

### ISSUE THREAD

**Issue by junliang230** [open-mmlab/mmdetection#2304]
target_stds value in rpn_head  and bbox_head are separatly  [1.0, 1.0, 1.0, 1.0] and [0.1, 0.1, 0.2, 0.2] in configs/faster_rcnn_r101_fpn_1x.py, but they are [0.07, 0.07, 0.11, 0.11]  and [0.05, 0.05, 0.1, 0.1] in configs/guided_anchoring/ga_faster_r50_caffe_fpn_1x.py. What is this value based on？？？thanks

**Comment by thisisi3** [comment]
As far as I know, they are the stds of the regressor output of a well-trained model. They are to help better train the regressor. I tested on VOC2007, the stds of bbox_head's regressor are indeed very close to target_stds. 

I think this value is related to the training IoU threshold of the bbox_head, because the target_stds in 2nd and 3rd bbox_head in CascadeRCNN have smaller values.  Does it apply to guided anchor? Sorry I am not familiar with guided anchor.

**Comment by breezelj** [comment]
@thisisi3 what do you mean a well-trained model ?

**Comment by thisisi3** [comment]
I would guess in the begining of the training, the stds would be different.

**Comment by abcxs** [comment]
I'm also very confused about this
