### ISSUE TITLE
How to reproduce trained model ?

### ISSUE THREAD

**Issue by yossibiton** [open-mmlab/mmdetection#2311]
This a general question - the repository has many trained model available for download, but it's not clear what were the parameters used for the training.

I will give a specific example.
In the [hrnet page](https://github.com/open-mmlab/mmdetection/tree/master/configs/hrnet) there is a model named HRNetV2p-W48 (in the FCOS table), but i have no idea how to train such model because some details are missing (and as we know god is in the details) :
1. there is no config file for that model
2. even if there were such config file the number of GPU's used for training is not mentioned (and that parameter affects the batch size)

I would love to get some clues and explanation about this reproducibility issue.

**Comment by hellock** [comment]
1. We provide most of config files for reproducing the models in our model zoo. While some methods can be easily obtained by combining components of other configs, we just ignore them for the simplicity of maintainance.
2. As mentioned in the documentation, all models are trained with 8 GPUs except that otherwise mentioned.

**Comment by yossibiton** [comment]
Thank you very much, i missed the part in the documentation when 8 GPUs is mentioned.
I also want to recommend to add the number of GPU's into the config, to avoid misunderstanding.
