### ISSUE TITLE
Questions about target_means and target_stds.

### ISSUE THREAD

**Issue by wiseholic** [open-mmlab/mmdetection#256]
I'm not sure it is correct to ask here or not, but it just for discussion.
In the config files the ``target_means`` and ``target_stds`` is used to normalized ``delta_x, delta_y, delta_w, delta_h`` (scale factor for bounding box to target mapping). I have some questions related to that.

1. How and when are these values calculated? Is that the statistics of the output bounding boxes after the network converged or not. 
2. When training the network, as the epoch increases, the network hasbetter bounding boxes. Hence, the ``delta`` is getting smaller overtime, is there any problem if we set fixed normalization factors for the bounding.

**Comment by ZwwWayne** [comment]
Hi @wiseholic ,
The target_means and target_stds are kind of convention originate from the earliest codebase https://github.com/rbgirshick/py-faster-rcnn.
1. It should be calculated before training.
2. This hyperparameter should not be changed during training, otherwise the target of the same anchor will change during change.
