### ISSUE TITLE
ann_info is loaded and parsed many times

### ISSUE THREAD

**Issue by imistyrain** [open-mmlab/mmdetection#2683]
**parse anno_info once**

**Improve train speed**
In [xml_style.py](https://github.com/open-mmlab/mmdetection/blob/93de55a62a88cba979c9d5e979b26f41546e2105/mmdet/datasets/xml_style.py#L63) and [coco.py](https://github.com/open-mmlab/mmdetection/blob/93de55a62a88cba979c9d5e979b26f41546e2105/mmdet/datasets/coco.py#L90) get_ann_info() try to load and parse anno_info again and again, which would reduce train speed. It should be better to load once.

**Comment by ZwwWayne** [comment]
The concern is that if the code only loads those annotations once, it will cause large memory usage before training and will also slow down the training initialization. 
However, since the data loader use workers, the loading for each frame's annotation does not cost much.
You can try to implement your idea and compare the speed. PRs are welcomed.
