### ISSUE TITLE
Support for Pascal VOC Instance Segmentation

### ISSUE THREAD

**Issue by TonyLianLong** [open-mmlab/mmdetection#2862]
**Describe the feature**
Currently, mmdetection only support Pascal VOC detection. However, Pascal VOC has segmentation support. I wonder if this is also going to be supported. 

**Motivation**
It is a small dataset for getting a taste of the performance of a model.

**Related resources**
There are multiple resources online about Pascal VOC's segmentation.
https://github.com/JackieZhangdx/InstanceSegmentationList

**Comment by hellock** [comment]
PASCAL VOC is usually used for semantic segmentation and rarely for instance segmentation, thus we have no recent plan to support it. PRs are welcome.

**Comment by TonyLianLong** [comment]
Got it. Thanks!

**Comment by tooHotSpot** [comment]
Hello! I have been watching this issue because of requirement to test instance segmentation performance on VOC. I have developed a small script to get instance segmentation masks here, take a look for a general idea. Some converted annotation files may be posted there later for convenience (or a patch with annotation errors improved)

https://github.com/tooHotSpot/FGN/blob/main/datasets/voc/voc_ds_parse.py
