### ISSUE TITLE
Using args.options to specify data_root seems infeasible

### ISSUE THREAD

**Issue by GengDavid** [open-mmlab/mmdetection#2957]
Since ```ann_file``` and ```img_prefix``` depend on ```data_root```, when the config is built before ```merge_from_dict```, specifying ```data_root``` via``` args.options``` can only replace ```data_root``` variable but has no effect on ```ann_file``` and ```img_prefix```
https://github.com/open-mmlab/mmdetection/blob/99a31d25b4d685da5ae868776a0483b80e8fb903/tools/train.py#L68-L70

**Comment by wscjxky** [comment]
thank u , i have the same problem  .  and i want to  transmit the `data_root`  to the configuration file dynamically .

and i use 
--options `"data.train.dataset.ann_file=['/home/xky/work/datasets/voc/VOCdevkit/VOC2012/ImageSets/Main/trainval.txt']"`  and i failed

**Comment by hyz-xmaster** [comment]
Hi, @xvjiarui,  I also have an problem with [--options](https://github.com/open-mmlab/mmdetection/blob/8bc0b9ce6d7d0656a8476ee8f31fa0441f8c4319/tools/test.py#L141)  when using it with test.py. 

Since --options arguments are only read into the dataset class in [test.py](https://github.com/open-mmlab/mmdetection/blob/8bc0b9ce6d7d0656a8476ee8f31fa0441f8c4319/tools/test.py#L142-L145), so if you would like to use --options to change parameters like samples_per_gpu or workers_per_gpu, there would be an error. This leads to different behaviours of --options when using with train.py and test.py. Hope this difference can be cleared.

**Comment by xvjiarui** [comment]
Hi @GengDavid @wscjxky 
As pointed out [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/config.md#use-intermediate-variables-in-configs), modifying intermediate variables in the children configs won't have effect unless the variables referenced it are also changed.

**Comment by xvjiarui** [comment]
@wscjxky You may also need to modify `img_prefix`.

**Comment by xvjiarui** [comment]
@hyz-xmaster 
You are right. The `train.py` and `test.py` handle `--options` differently. You are very welcomed to create a PR to unify them.

**Comment by hyz-xmaster** [comment]
> @hyz-xmaster
> You are right. The `train.py` and `test.py` handle `--options` differently. You are very welcomed to create a PR to unify them.

I am afraid I am not available for that fix. As you are very familiar with the whole codebase, you will be the best person for doing that when you are available. Thanks.

**Comment by GengDavid** [comment]
@xvjiarui Thx, changing all referenced does work but is a little bit inconvenience.
