### ISSUE TITLE
 ('MMDataParallel only supports single GPU training, if you need to' AssertionError: MMDataParallel only supports single GPU training, if you need to train with multiple GPUs, please use MMDistributedDataParallelinstead.

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmdetection#3116]
```
 ('MMDataParallel only supports single GPU training, if you need to'
AssertionError: MMDataParallel only supports single GPU training, if you need to train with multiple GPUs, please use MMDistributedDataParallelinstead.
```

**Comment by jinfagang** [comment]
OK, seems need specific launcher default is none. However using pytorch as default got:

```
    raise KeyError(key) from None
KeyError: 'RANK'
```

**Comment by hellock** [comment]
We gave up the support for multi-GPU training with DataParallel any more since there is no advantage over DistributedDataParallel.

**Comment by jinfagang** [comment]
@hellock  But it can not work out of box now when using multi-gpu on one machine.
It claims need several envriment variables which seems hard to set

**Comment by mathmanu** [comment]
@hellock DataParallel was working alright just a couple of weeks ago. Is this change due to some new issue? If not, would you consider making that a warning instead of an assert?

As the above thread said, DataParallel is easier to use. It also shuts down more gracefully. With DistributedDataParallel, when I press Ctrl^C, but sometimes the underlying process doesn't get shutdown and I have to kill it explicitly.

**Comment by mathmanu** [comment]
I commented out the assert in MMDataParallel and ran the training, it works! (I have switched off evaluation during training).

**Comment by mathmanu** [comment]
Hi, Another observation is that training DistributedDataParallel uses more CPU and GPU memory compared to training with DataParallel. Found couple of threads talking about by searching (For example: https://discuss.pytorch.org/t/is-it-expected-for-distributeddataparallel-to-use-more-memory-on-1-gpu-in-a-1gpu-1process-setup/77748/2) - that says it is a limitation - not sure.

**Comment by hellock** [comment]
> @hellock But it can not work out of box now when using multi-gpu on one machine.
> It claims need several envriment variables which seems hard to set

For multiple GPUs on a single machine, it just works as simple as DataParallel and no additional environment variable is needed. `./dist_train.sh` is enough.

**Comment by hellock** [comment]
> @hellock DataParallel was working alright just a couple of weeks ago. Is this change due to some new issue? If not, would you consider making that a warning instead of an assert?
> 
> As the above thread said, DataParallel is easier to use. It also shuts down more gracefully. With DistributedDataParallel, when I press Ctrl^C, sometimes the underlying process doesn't get shutdown and I have to kill it explicitly.

To support the multi-GPU mode of DataParallel, we need to overwrite a few more methods to add two apis [`train_step()`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/parallel/data_parallel.py#L14) and [`val_step()`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/parallel/data_parallel.py#L33). There is a trend to discard DataParallel since it is twice slower than DistributedDataParallel and some new projects/repos only support DistributedDataParallel.

**Comment by TangDL** [comment]
> I removed the assert in MMDataParallel and ran the training, it works! (I have switched off evaluation during training).
you are a small jilin ghost
