### ISSUE TITLE
how to cache images to speed up the training process

### ISSUE THREAD

**Issue by CarryHJR** [open-mmlab/mmdetection#3257]
**Describe the feature**
cache images to speed up the training process
**Motivation**
my computer is a old HDD, my ram is ddr4 128Gb, thus i wanna cache the whole images into the ram, I believe this will speed up the training process

**Comment by ZwwWayne** [comment]
This feature usually needs to be implemented in other places rather than in mmdet. MMCV already implements some [file clients](https://mmcv.readthedocs.io/en/latest/api.html#mmcv.fileio.FileClient) for data loading, they might help. You can use them by setting ``file_client_args`` in the configs of data loading modules like [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/loading.py#L34).

**Comment by CarryHJR** [comment]
thanks, i got it
