### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by wuhaonanBOB** [open-mmlab/mmdetection#3296]
I have trained my custom dataset with detectors_cascade_rcnn_r50_1x_coco.py and get checkpoints/latset.pth.
but I test with command "python tools/test.py configs/detectors/detectors_cascade_rcnn_r50_1x_coco.py chectpoints/latest.pth --eval bbox"
it occurs the follow error:
![image](https://user-images.githubusercontent.com/57397434/87275398-8f25f700-c510-11ea-9a53-2ebe53ecb3fe.png)
can you help me? thank you.

**Comment by sunnyisabaster** [comment]
same as yours. This problem nagged me for days. Have you solved this problem? I changed num_classes from 80 to 1 bc I only need to detect one object in my project, then it occurred this problem when I  trained my custom dataset with cascade_rcnn_x101_64x4d_fpn_20e_coco.py.

**Comment by sunnyisabaster** [comment]
@ZwwWayne

**Comment by OOIIps** [comment]
@sunnyisabaster I have same error. How do you fix this problem ?

**Comment by sakurasakura1996** [comment]
Have anyone solved this prolem? I have same problem.

**Comment by ZwwWayne** [comment]
This is usually because the `num_classes` in the head is greater than the real number of categories in your dataset. For example, the `num_classes` in the head is set to be 8, thus the prediction will predict label to be 8 sometimes, but your dataset only contain 7 categories, then it will cause the described issue.
