### ISSUE TITLE
ValueError: All dicts must have the same number of keys

### ISSUE THREAD

**Issue by Note-Liu** [open-mmlab/mmdetection#3345]
for train ,if i use --gpus 1,it works well,if i use --gpus 2 :  ValueError: All dicts must have the same number of keys.
how to solve it?

**Comment by ZwwWayne** [comment]
Please use the `Error Template` to describe what you have done and how to reproduce the bug clearly.

**Comment by Note-Liu** [comment]
![not solve](https://user-images.githubusercontent.com/45785807/87872320-ec76e800-c9e9-11ea-8f53-24cde03f48b7.png)

**Comment by Note-Liu** [comment]
My problem is similar to the one described in this link:
https://github.com/open-mmlab/mmdetection/issues/2303#issue-585397849

**Comment by shaunzhuyw** [comment]
emmmm....... I encounter the same question and can't solve it

**Comment by pdpdpd2013** [comment]
I also encounter the same problem. Any one knows how to fix it?

**Comment by ZwwWayne** [comment]
It might because that you data has some dicts but they contain different keys, you may check the data pre-process process by setting samples_per_gpu=1 and compare the data dicts in different iterarions.

**Comment by pdpdpd2013** [comment]
For me, I find out there are some images with no annotated bboxes. After filtering out these images from the training set, this problem disappears magically!

**Comment by pdpdpd2013** [comment]
This only happens when the version of your mmdetection is low. In bbox_head.py, the loss function returns a dict. If there is no foreground bounding boxes, the losses is not assigned with the key 'loss_bbox'. This may cause error for parallel training on multiple GPUs, since the number of keys in losses are different.

For your case, you can try to modify `mmdet/models/roi_heads/bbox_heads/bbox_head.py`, add the following lines in the function loss():

```
    if pos_inds.any():
        ...

    # add the following two lines
    else:
        losses['loss_bbox'] = bbox_pred.sum() * 0
```

I find out that in the latest version of mmdetection (2.4), this problem has already been solved.
See `mmdet/models/roi_heads/bbox_heads/bbox_head.py` for more details.
