### ISSUE TITLE
why not use im2col_step in ModulatedDeformableConvolutionOp?

### ISSUE THREAD

**Issue by Google1234** [open-mmlab/mmdetection#340]
use im2col_step in DeformableConvolutionOp, so we wonder : why not use im2col_step in ModulatedDeformableConvolutionOp?

**Comment by Google1234** [comment]
use im2col_step in DeformableConvolutionOp, so we wonder : why not use im2col_step in ModulatedDeformableConvolutionOp?

**Comment by RangiLyu** [comment]
@grimoire

**Comment by grimoire** [comment]
`im2col_step` in DCN is used to limit memory usage.
Since DCN and modulated DCN generate kernels for each pixel on the feature map which is different from the common conv layer. We use `im2col` to do the convolution instead.
`im2col` requires a lot of memory to do the job. Especially when `batch size` is large. So we split `batch` by `im2col_step` [here](  https://github.com/open-mmlab/mmcv/blob/004c00675f912b9ac59ba07655295c86a39e29d1/mmcv/ops/csrc/pytorch/deform_conv_cuda.cu#L264) to reduce memory usage.
Modulated DCN simply use `im2col_step=1` [here](https://github.com/open-mmlab/mmcv/blob/004c00675f912b9ac59ba07655295c86a39e29d1/mmcv/ops/csrc/pytorch/modulated_deform_conv_cuda.cu#L143) to minimize memory usage.
