### ISSUE TITLE
metric mAP is not supported

### ISSUE THREAD

**Issue by mytk2012** [open-mmlab/mmdetection#3429]
**Command line**:python tools/test.py configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc.py checkpoints/SOME_CHECKPOINT.pth --eval mAP
**Data folder**:data/coco/train2017 data/coco/test2017 data/coco/val2017 data/coco/annotations
**Others not changed****first run getting started**

**Comment by tojimahammatov** [comment]
you can see allowed metrics in dataset configs, and for coco I found that: 

`allowed_metrics = ['bbox', 'segm', 'proposal', 'proposal_fast']`

in **line 396** of **mmdet/datasets/coco.py** file.

**Comment by mytk2012** [comment]
> you can see allowed metrics in dataset files, and for coco I found that:
> 
> `allowed_metrics = ['bbox', 'segm', 'proposal', 'proposal_fast']`
> 
> in **line 396** of **mmdet/datasets/coco.py** file.

But  in configs\_base_\dataset\coco_detection.py  line48:evaluation = dict(interval=1, metric='bbox')
I think it should be allowed.And can you tell me why I can't debug this command using pycharm.It automatically runs.

**Comment by tojimahammatov** [comment]
Sorry, I did not fully understand you. Why can't you debug? 

In the line 48 of _coco_detection.py_, they have just passed one of the supported metric, `metric='bbox'`.

If you set `metric='mAP'` instead of that, it will finally be passed as a metric argument of a function in _mmdet/datasets/coco.py_ file (a function having line 396). Since mAP is not in the supported metric list, you get a message saying **"metric mAP is not supported"**. 

If you really want mAP, maybe you can implement and add your own.

**Comment by tojimahammatov** [comment]
> > you can see allowed metrics in dataset files, and for coco I found that:
> > `allowed_metrics = ['bbox', 'segm', 'proposal', 'proposal_fast']`
> > in **line 396** of **mmdet/datasets/coco.py** file.
> 
> But in configs_base_\dataset\coco_detection.py line48:evaluation = dict(interval=1, metric='bbox')
> I think it should be allowed.And can you tell me why I can't debug this command using pycharm.It automatically runs.

Sorry, I did not fully understand you. Why can't you debug?

In the line 48 of _coco_detection.py_, they have just passed one of the supported metric, `metric='bbox'`.

If you set `metric='mAP'` instead of that, it will finally be passed as a metric argument of a function in _mmdet/datasets/coco.py_ file (a function having line 396). Since mAP is not in the supported metric list, you get a message saying **"metric mAP is not supported"**.

If you really want mAP, maybe you can implement and add your own.

**Comment by hellock** [comment]
`bbox` means the bbox mAP for COCO.
