### ISSUE TITLE
Faster RCNN-std bettwen rpn and bbox

### ISSUE THREAD

**Issue by abcxs** [open-mmlab/mmdetection#3508]
In Faster RCNN, the STD used by RPN head is [1, 1, 1, 1], while that used by bbox head is [0.1,0.1,0.2,0.2]
1. Why are the settings of RPN and Bbox head different?
2. Why does the STD of Bbox head need to be set like [0.1, 0.1, 0.2, 0.2]

**Comment by ZwwWayne** [comment]
1. The settings of RPN and Bbox head are different because the distribution of boxes is different. RPN usually relies on anchors, which have large gap between the ground truth boxes, while the box head's regression is based on the proposals, which are close to the ground truth boxes.
2. Similar reason as 1, the std is usually smaller. [0.1, 0.1, 0.2, 0.2] is hyper-parameters, of course you could tune that to see whether other settings are better. But we usually do not do that because this should have been tuned since faster r-cnn.

**Comment by abcxs** [comment]
@ZwwWayne thanks.
