### ISSUE TITLE
Is there a way to convert an customized mmdetection model ?

### ISSUE THREAD

**Issue by hoangkhoiLE** [open-mmlab/mmdetection#3644]
Hello,
Currently i'm interesting at excellent model https://github.com/saic-vul/iterdet which is based on your execellent work. But i can't not using your file in ./tools/pytorch2onnx.py to convert of the model because of the incompatible the input of model iterdet. Looks like https://github.com/saic-vul/iterdet/blob/master/tools/pytorch2onnx.py#L113 input_data should be a tuple ((1, 3, w, h), (1, 1, w, h)) following the guide of author (https://github.com/saic-vul/iterdet/issues/21). But I don't know how to fix that. Can you show me the way or some guide to convert this model to onnx. Thank you a lot.

This is the first error that i don't know how to fix
![image](https://user-images.githubusercontent.com/57557628/91568787-e576ba00-e945-11ea-9826-67040e5284f5.png)

Best regard

**Comment by yhcao6** [comment]
@drcut Could you help check this issue?

**Comment by drcut** [comment]
Hi, 
Thank you for reaching out with your questions.
I have looked through that repo and found it is based on mmdet version v2.0.0. However, the pytorch2onnx part of mmdet was significantly changed after v2.3.0, and the old api was not supported anymore.
From the log you shared, it seems it's not a error raised from Pytorch2ONNX part, but from build_detector part, which are used not only for deployment but also for training.
So I suggest you can first reproduce that repo's result on Pytorch, and then concerning convert that model to ONNX.
BTW, I guess this error is due to the incompatible of mmcv version and mmdet version.

**Comment by hoangkhoiLE** [comment]
@drcut  Thank you for your kind advice to a newbie in a domain like me. Can you give me some others advices or documents at how to reproduce a repo from mmdet to raw pytorch ?

Best regard

**Comment by drcut** [comment]
> @drcut Thank you for your kind advice to a newbie in a domain like me. Can you give me some others advices or documents at how to reproduce a repo from mmdet to raw pytorch ?
> 
> Best regard

You are welcomed. Sorry, there seems some misleading. I mean that this repo (`iterdet`) mainly focused on training. So I believe there are some commands that can be executed correctly. 
Like the below command they provided in `ReadMe`:
```bash
bash tools/dist_test.sh configs/iterdet/crowd_human_full_faster_rcnn_r50_fpn_2x.py \
    work_dirs/iterdet/crowd_human_full_faster_rcnn_r50_fpn_2x/latest.pth 8
```
Can you run this command correctly?

**Comment by hoangkhoiLE** [comment]
Thank you and sorry for my late reponse. Currently, i have change the model principal so i can't continue on this. Thank a lot for your support.
