### ISSUE TITLE
How to modify the number of channels of the input image?

### ISSUE THREAD

**Issue by ma3252788** [open-mmlab/mmdetection#3820]
Where can I change the number of channels of the input image? I have customized a convolution kernel, which can modify the channel. When the number of channels does not change, the code runs very well, when the number of channels becomes 4 times the original, I get an error:
```
RuntimeError: Given groups=1, weight of size 256 12 7 7, expected input[2, 3, 800, 1216] to have 12 channels, but got 3 channels instead
```
I want to know where can I set the number of channels of the image? My image is VOC, its input channel is 3, I don’t want it 12. Please tell me where I can set the number of input channels.

Thank you for any help!!!!

**Comment by RyanXLi** [comment]
Please distinguish between the in_channels and out_channels of a convolution layer, as described [here](https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html) in the PyTorch Conv2d documentations. Simply speaking, in_channels is the number of channels in each conv filter and it has to match the number of channels in the input image(3 in your case because of RGB), while out_channels is the number of conv filters, which corresponds to the number of output feature maps.
