### ISSUE TITLE
How to use FileClient  to speed?

### ISSUE THREAD

**Issue by noprohuangqi** [open-mmlab/mmdetection#3862]
I found mmdetection has provided the file-client function to speed up io.
  
`_backends = {
        'disk': HardDiskBackend,
        'ceph': CephBackend,
        'memcached': MemcachedBackend,
        'lmdb': LmdbBackend,
    }`
  
But I do not know how to use this and there is no document to read.
So I want to get help for this.

**Comment by ZwwWayne** [comment]
Please refer to the [doc in mmcv](https://mmcv.readthedocs.io/en/latest/_modules/mmcv/fileio/file_client.html?highlight=fileclient). If you installed ceph of LMDB in your system and use them for data io, then you can use these backends to accelerate your data io. Otherwise, you could only use the HardDiskBackend.
