### ISSUE TITLE
Normalize std for widerface

### ISSUE THREAD

**Issue by zehuichen123** [open-mmlab/mmdetection#3964]
Hi, I am trying to run widerface dataset under mmdet framework. However, I notice that std for widerface is different from others like coco or voc, with an std = [1, 1, 1]. Is this right?
Here is the code link:
https://github.com/open-mmlab/mmdetection/blob/9caa197f3d518659b7218683b976b02986c78dc6/configs/_base_/datasets/wider_face.py#L4

**Comment by yhcao6** [comment]
`img_norm_cfg` should be consistent with the pre-trained models. Since in the [config](https://github.com/open-mmlab/mmdetection/blob/master/configs/wider_face/ssd300_wider_face.py) the pre-trained model is `SSDVGG`, the the img_norm and std is the same as [`SSDVGG`](https://github.com/open-mmlab/mmdetection/blob/9caa197f3d518659b7218683b976b02986c78dc6/configs/ssd/ssd300_coco.py#L8)

**Comment by zehuichen123** [comment]
Got it! Thx!
