### ISSUE TITLE
Why does the bounding box become so loose after rotation data aug? Is there a better way

### ISSUE THREAD

**Issue by rra94** [open-mmlab/mmdetection#4070]
Hey, I noticed that the bounding boxes after data augmentation become very loose. Is there a way to correct this?

before rotation
![image](https://user-images.githubusercontent.com/5424122/98279623-2ef80c80-1f68-11eb-9b71-167c110034bd.png)

after 115 degree rotation
![image](https://user-images.githubusercontent.com/5424122/98279637-33242a00-1f68-11eb-9a56-bb994f2cc6dc.png)

**Comment by v-qjqs** [comment]
Hi @rra94, it's normal that the bounding box becomes loose when rotation is called, especially for large angle of rotation. Since the four corners of the original bounding box is tranformed to another points according to the rotation matrix, and then the rotated bounding box is constructed to include all the translated points, so it's common that the rotated bounding box becomes loosser.

**Comment by mljack** [comment]
You could implement an augmentation method to recompute bounding box from polygon segmentation.
