### ISSUE TITLE
VFNET device error when run inference_detector

### ISSUE THREAD

**Issue by JonathanAndradeSilva** [open-mmlab/mmdetection#4146]
Hi everyone,

When a run the inference_detector to VFNET algorithm, I got this error message (only for VFNET, for ATSS ... no problems):

/usr/local/lib/python3.6/dist-packages/mmcv/parallel/_functions.py in forward(target_gpus, input)
     71             # Perform CPU to GPU copies in a background stream
     72             streams = [_get_stream(device) for device in target_gpus]
---> 73 
     74         outputs = scatter(input, target_gpus, streams)
     75         # Synchronize with the copy stream

/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/_functions.py in _get_stream(device)
    117     if _streams is None:
    118         _streams = [None] * torch.cuda.device_count()
--> 119     if _streams[device] is None:
    120         _streams[device] = torch.cuda.Stream(device)
    121     return _streams[device]

TypeError: list indices must be integers or slices, not torch.device

The device paramenter of init_detector is default ('cuda:0') and distributed=False. Can you help me?

**Comment by ggalan87** [comment]
I had the same problem with VFNet. I think it's a fundamental bug in the code of mmcv and nothing to do with the method. More specifically here:
https://github.com/open-mmlab/mmcv/blob/91a7fee03a3973a56cb5f687a6859ef0aaacf15e/mmcv/parallel/_functions.py#L72

However torch _get_stream formulates a list, therefore device should be integer and not torch.device  https://github.com/pytorch/pytorch/blob/18ae12a841bdc99c6cce65ac5c77cc1149dc8564/torch/nn/parallel/_functions.py#L111-L120

The fix is to pass device.index rather than device while calling _get_stream

**Comment by lfydegithub** [comment]
I have the same issue when i run vfnet demo. how to solve it?

**Comment by lfydegithub** [comment]
@JonathanAndradeSilva @ggalan87 I have found the reason.
in `vfnet_r50_fpn_1x_coco.py` test_pipline, change `dict(type='DefaultFormatBundle')` to `dict(type='ImageToTensor', keys=['img'])`
```python
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            # dict(type='DefaultFormatBundle'),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
```
