### ISSUE TITLE
how to print accuracy metric except precision and recall?

### ISSUE THREAD

**Issue by TuanNguyenSKKU** [open-mmlab/mmdetection#4189]
hi everyone,

I can print precision and recall by using the command: 
python tools/test.py configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py work_dirs/mask_rcnn_r50_fpn_1x_coco/latest.pth --eval bbox segm --out results.pkl

but how to print accuracy metric??
Thank you.

**Comment by yhcao6** [comment]
You can refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_runtime.md#customize-workflow. Change the trainset to your valset and change the workflow to [('val', 1)]

**Comment by TuanNguyenSKKU** [comment]
What can I do to print it out without having to train the model again?
I have already trained the model using the command: 
python tools/train.py configs/mask_rcnn/mask_rcnn_r101_fpn_1x_coco.py --validate

**Comment by yhcao6** [comment]
There is no implemented interface to computing accuracy. But you can implement it yourself. Since you are using Mask Rcnn, here are some simple instructions:
1. Forward an image to get classification scores of each RoI
2. Assign gt target to each RoI to get its corresponding labels
3. With the assigned labels, you can compute the accuracy of this image
4. Take the average over the whole validate set

**Comment by TuanNguyenSKKU** [comment]
Thank you for your suggestions.
