### ISSUE TITLE
How to save images ?

### ISSUE THREAD

**Issue by Adblu** [open-mmlab/mmdetection#4194]
Lets say I am training the model for example using htc architecture. 
Here is part of my config file:

```
dict(
    type='Albu',
    transforms=[
        dict(
            brightness_limit=0.2,
            contrast_limit=0.2,
            p=0.5,
            type='RandomBrightnessContrast'),
        dict(type='HueSaturationValue'),
        dict(
            p=0.5,
            quality_lower=80,
            quality_upper=99,
            type='JpegCompression'),
        dict(type='RandomShadow', p=0.3),
        dict(type='Equalize', p=0.3),
        dict(type='Downscale', p=0.3),
        dict(type='FancyPCA', p=0.3),
        dict(type='RandomRain', drop_length=10, blur_value=1, p=0.3)
    ]),
```

The question is, when augmentation happens, those images are inserted straight into the training. Is there possibility to save them physically ?
I am asking only because I need to keep track of exact images used for training.

**Comment by GiangHLe** [comment]
Assume that you don't have custom pipeline in custom dataset, they load the image in `./mmdetection/mmdet/datasets/pipeline/compose.py`. In `__call__` function, line 40, that data contain your image, because they store image in an object named `DataContainer` so you can take your image after augment by `image = data['img']._data`, then continue to process convert torch to numpy.

**Comment by Adblu** [comment]
Perfect, thanks !

**Comment by waddington** [comment]
@GiangHLe did you make any progress with this? I am attempting to do the same but the colours in my images are all messed up.

**Comment by GiangHLe** [comment]
@waddington It's weird, can you provide the script that you used to get the image? 

Besides that, I haven't used mmdetection since last Christmas. There are some new updates that I might not know.
