### ISSUE TITLE
feature request: coco dataset categories merge into supercategories

### ISSUE THREAD

**Issue by cissoidx** [open-mmlab/mmdetection#4226]
**Describe the feature**
Can we use only the supercategories in training and testing while ignoring categories? Annotations might have been done in a very detailed way, but it often turns out that models cannot handle very similar objects with different category labels, models never converge. So merging similar categories into one could be a good compromise.

I am not so sure that if mmdet supports this, and I have searched in the code for clues but in vain. I guess this is very commonly demanded in real cases.

**Comment by ZwwWayne** [comment]
Hi @cissoidx ,
For your case, you can update your annotation files and merge them in your annotation then use them for training.
Since the rules for merging supercategories varies across different scenarios, we might not be able to find a universal rule for that and add it in mmdetection. But thanks for your kind advice, we will consider it in the future.
