### ISSUE TITLE
Different mean values of image normalization for HRNet

### ISSUE THREAD

**Issue by ycszen** [open-mmlab/mmdetection#4232]
I find the different configs of HRNet experiments use different mean values for image normalization.

For example,
[fcos_hrnetv2p_w32_gn-head_4x4_1x_coco.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/hrnet/fcos_hrnetv2p_w32_gn-head_4x4_1x_coco.py) uses the `[102.9801, 115.9465, 122.7717]` as the mean value,
while [fcos_hrnetv2p_w32_gn-head_mstrain_640-800_4x4_2x_coco.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/hrnet/fcos_hrnetv2p_w32_gn-head_mstrain_640-800_4x4_2x_coco.py) uses the `[103.530, 116.280, 123.675]` as the mean value.

Which one is correct?

**Comment by ZwwWayne** [comment]
Thanks for pointing it out.
According to their official pre-training [here](https://github.com/HRNet/HRNet-Image-Classification/blob/master/tools/train.py#L144), the image norm should be the same as our default image norm in [coco_detection.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/datasets/coco_detection.py). So the HRNet models of FCOS all uses the wrong image norms because they inherit the config of FCOS.

**Comment by ycszen** [comment]
Thanks for your fast reply. 
I will re-run with the mentioned image norm to check it.
