### ISSUE TITLE
[FocalLossCost] Fusion Pos and Neg terms

### ISSUE THREAD

**Issue by TuanTNG** [open-mmlab/mmdetection#4559]
I read the [class FocalLossCost](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/bbox/match_costs/match_cost.py#L97) in line 97. As far as I understand, the term cls_cost should be pos_cost[:, gt_labels] `+` neg_cost[:, gt_labels] instead of pos_cost[:, gt_labels] `-` neg_cost[:, gt_labels].

Is there anything wrong here?
Thank you

**Comment by jshilong** [comment]
I believe that the current implementation is correct. The code is calculating the cost of dividing this point into a positive sample because there is no definite label for this point. If we do as you say, a point with high confidence such as 0.999, this point will get a very large `cls_cost` and cannot be matched as a positive sample, which is obviously unreasonable

**Comment by jshilong** [comment]
Or you can understand it this way, the smaller the `pos_cost` indicate that this point is more like a positive sample,  and the smaller `neg_cost` indicate this point is more like a negative sample, so  `pos_cost - neg_cost`  is a value related to whether this point is a positive sample.

**Comment by TuanTNG** [comment]
Thank you for your careful explanation.  Your answer is very clear and straight forward.
I got it.

Thank you so much.
