### ISSUE TITLE
Question on roi_extractor's source code.

### ISSUE THREAD

**Issue by thisisi3** [open-mmlab/mmdetection#4690]
https://github.com/open-mmlab/mmdetection/blob/68d860d6f1a4a1fb687f2512038f2cbce7c6b08d/mmdet/models/roi_heads/roi_extractors/single_level_roi_extractor.py#L79

This line is from mmdet-v2.3.0.
What is the purpose of this line? Does it affect training or simple to avoid runtime bug.

**Comment by ZwwWayne** [comment]
This is because sometimes some pyramid levels will not be used for ROI feature extraction and this will cause an incomplete computation graph in one GPU, which is different from those in other GPUs and will cause a hanging error. Therefore, we add it to ensure each feature pyramid is included in the computation graph to avoid runtime bugs.
We will add comments on that line to avoid errors.
