### ISSUE TITLE
Should I use different loss weights in both rpn_head and roi_head to re-weight the loss element-wisely?

### ISSUE THREAD

**Issue by fzfs** [open-mmlab/mmdetection#4714]
Hi，thanks for your code！

I want to re-weight the loss element-wisely, should I use different loss weights in both rpn_head and roi_head?

And why the function get_targets() in class [AnchorHead](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/anchor_head.py)  has arg img_metas, but the function get_targets() in class [BBoxHead](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/anchor_head.py)  does not have arg img_metas ?

**Comment by yhcao6** [comment]
`loss_weight` in the config:
https://github.com/open-mmlab/mmdetection/blob/8824417be9218e9c300c13dcd2ade46958002f3c/configs/_base_/models/faster_rcnn_r50_fpn.py#L31-L32

is not used for elementwise reweighting.
To element-wisely re-weight the loss, you need to define a new label_weight:

https://github.com/open-mmlab/mmdetection/blob/8824417be9218e9c300c13dcd2ade46958002f3c/mmdet/models/roi_heads/bbox_heads/bbox_head.py#L232-L237.

The `get_targets()` function in AnchorHead has arg `img_metas` because it needs some information that can be extracted from `img_metas`, but in BBoxHead it doesn't.

**Comment by fzfs** [comment]
Thanks for your reply！
I know loss_weight in the config is not used for elementwise reweighting. 
To element-wisely re-weight the loss, should I define two weights for class rpn_head and class roi_head, respectively?

**Comment by yhcao6** [comment]
Yes, the loss of RPNHead and BBoxHead are computed separately.

Take faster-rcnn as an example,

For RPNHead:
https://github.com/open-mmlab/mmdetection/blob/8824417be9218e9c300c13dcd2ade46958002f3c/mmdet/models/dense_heads/anchor_head.py#L376-L424

For BBoxHead,
https://github.com/open-mmlab/mmdetection/blob/8824417be9218e9c300c13dcd2ade46958002f3c/mmdet/models/roi_heads/bbox_heads/bbox_head.py#L218-L267

**Comment by fzfs** [comment]
Thanks!
To define two weights for class rpn_head and class roi_head, respectively, I think arg img_metas exists in get_targets() function in both AnchorHead and BBoxHead would be good. Because the weights can be defined by img_metas in the loss of RPNHead and BBoxHead.

**Comment by yhcao6** [comment]
In my opinion, defining the weight of loss usually doesn't need `img_metas`. But if you need it, you can pass them to the corresponding functions.

**Comment by fzfs** [comment]
Yes, I have passed them to the corresponding functions.
If the weight is related to every image, a id can be defined in img_metas to generate different weights.

**Comment by jamesbc123** [comment]
@fzfs can you share how you made a weight for each label using img_metas. Do you know how to edit this weight during training? I would like to edit each label weight after calculating the loss.

Thanks
