### ISSUE TITLE
Issues with 'category_id' on COCO and Confidence score

### ISSUE THREAD

**Issue by LourencoVazPato** [open-mmlab/mmdetection#474]
I am new to object detection and I have been experimenting with this repository for the past few months. I've found two small issues.

1. The category ids produced by the detectors in mmdetection are different from the ones used in the COCO dataset (the ids from COCO skip some numbers while in mmdet they go from 0 to 80). This is easily fixed but I was wondering if there is something I am doing wrong in my inference code.

2. The detectors generate a bunch of low confidence bad detections. Do these detections hurt the AP performance? Is there any thresholding applied to the detections in order to improve the AP?

**Comment by OceanPang** [comment]
@LourencoVazPato 
1. The mismatch between the ids in mmdetection and COCO dataset is due to the categories of ''stuff'' things, such as air, road, which are used in semantic segmentation but cannot be counted and used in object detection and instance segmentation. Therefore, you must map the ids in COCO to a continuous sequence to train the model, and later remap it to the original ids to evaluate the results.
2. The results with low confidence won't hurt the AP performance. I recommend you to read the mAP in PASCOL VOC to understand the process.
