### ISSUE TITLE
[>>>>>>>>>>                                        ] 1022/5000, 1.5 task/s, elapsed: 673s, ETA:  2621s已杀死

### ISSUE THREAD

**Issue by WYQ-Github** [open-mmlab/mmdetection#5263]
测试模型到一半出现被杀死的情况，请问出现这个问题的原因是什么？该如何解决？

**Comment by AronLin** [comment]
Can you provide more details, such as the environments, the version of mmdet and mmcv,  the command you run etc.

Without more details, if your system is Linux, I guess your process was killed by the system because it used too much memory and CPU. You can run the below command to check if the system killed your process :

    sudo egrep -i -r 'killed process' /var/log
Linux detects changes in memory, and if it finds a process that is using too much memory, it is killed to protect the system. A possible solution is increasing the virtual memory.

Please give me more details if my guesses are not correct.

**Comment by WYQ-Github** [comment]
大佬你好，感谢你的解答。确实如你所说的，因为内存的原因出现了以上的错误，听从了你的建议增加了虚拟内存解决了这个问题。谢谢！
