### ISSUE TITLE
Questions about pretrained weights

### ISSUE THREAD

**Issue by isomatical** [open-mmlab/mmdetection#5394]
My questions are as followes:
1. I want to customize a model, e.g. Cascade RCNN with ResNeXt-101 as backbone and PAFPN as neck, but there are no pretrained weights for the whole entire stucture. Due to limited resources, I can't train it from scratch on COCO. So what else can I do with it?
2. After I modified the neck part from FPN to PAFPN, I still tried to load the "Cascade RCNN X-101-64x4d-**FPN**" pretrained weights. Surprisingly no errors were reported, making me wonder what extractly was going on under the hood? Clearly the weights for FPN could not be loaded into the model since the structure of neck has changed. Does mmdetection has some mechanism to deal with such incompatibility, like when incompatibility occurs in this example, only the backbone weights are loaded into the model, and the neck part remains default initialization values?
3. A bit similar to question 2: Can I only load the backbone weights into the model? If the answer is yes, how can I do it?

**Comment by ZwwWayne** [comment]
1. we are not able to help either, you may still considering load Cascade R-CNN + ResNeXt-101 FPN as pretrain.
2. This is because PAFPN extend FPN by one more path, they share some conv layers. Thus, when the checkpoint lack some keys, it will be fine and the program will continue as we set strict=False. When incompatibility occurs, the weights that mismatch will not be loaded.
3. You can manually modify the keys in the checkpoints and throw those in head and neck.
