### ISSUE TITLE
torch serve unregistered model

### ISSUE THREAD

**Issue by FirasKedidi** [open-mmlab/mmdetection#5538]
Hello,
i want to use torch serve to deploy my model . Wen running torchserve --start i get this error that the model is unregistered. 

![image](https://user-images.githubusercontent.com/58661767/124494570-eae73100-ddae-11eb-9899-22794a4fbf23.png)

Can you help me please.

**Comment by hhaAndroid** [comment]
Hi @FirasKedidi Are you using docker/serve and related commands directly？

**Comment by FirasKedidi** [comment]
no i am using colab i didn't run docker

**Comment by ddonatien** [comment]
Hi @FirasKedidi, your error is not the the model is unregistered. Torch serve unregistered your model because of the previous error of not being able to bind the the localhost address.
Some program is using the port 8080. On ubuntu you can check which one with the following command : `lsof -i :8080`

**Comment by FirasKedidi** [comment]
The problem is from colab i runned locally and it worked.
