### ISSUE TITLE
add solov2 network

### ISSUE THREAD

**Issue by chensen668** [open-mmlab/mmdetection#5556]
When can mmdet realize solov2 network? There are too few instances of network segmentation.

**Comment by AronLin** [comment]
We are designing the basic model for one-stage instance segmentation and panoptic segmentation. Panoptic FPN, SOLO, SOLOv2, and CondInst are listed as the main methods to be released in the next two months.

**Comment by chensen668** [comment]
thanks



---Original---
From: "Guangchen ***@***.***&gt;
Date: Wed, Jul 7, 2021 15:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmdetection] add solov2 network (#5556)




 
We are designing the basic model for one-stage instance segmentation and panoptic segmentation. Panoptic FPN, SOLO, SOLOv2, and CondInst are listed as the main methods to be released in the next two months.

**Comment by PushpakBhoge** [comment]
Hi 
any progress on this ?
SOLOv2 s already implemented with mmdet in this repo https://github.com/WXinlong/SOLO/tree/master/configs/solov2
But the development is branched out at some older version of mmcv and mmdet
I think we should be able to merger by making some compatability adjustment
can anyone point to any code structure documents ? 
asking because I would be glad to contribute :)

**Comment by AronLin** [comment]
> Hi any progress on this ? SOLOv2 s already implemented with mmdet in this repo https://github.com/WXinlong/SOLO/tree/master/configs/solov2 But the development is branched out at some older version of mmcv and mmdet I think we should be able to merger by making some compatability adjustment can anyone point to any code structure documents ? asking because I would be glad to contribute :)

The solov2 and condinst are blocked now. We will be glad if you can contribute. You can refer to the structure of SOLO in mmdet, they are all one-stage methods.
