### ISSUE TITLE
Weird mask inference results

### ISSUE THREAD

**Issue by kczarnota** [open-mmlab/mmdetection#5612]
I followed the steps described in https://github.com/open-mmlab/mmdetection/blob/master/docs/2_new_data_model.md to train mask rcnn model on my clothes dataset. I created the annotation .json files, loaded them in FiftyOne software (the one linked on official coco site) to check if images look good and everything was fine. The training process was smooth. After loading the trained model and the inference I noticed that predicted masks looks weird (see attached photo and those weird snake-like lines). I tried to debug the problem by visualizing masks in training loop when they are taken from data loader and there are no problems there. Can anyone help me with finding the cause of this problem?
![res](https://user-images.githubusercontent.com/9088954/125627589-add1b20e-0bbb-469f-94f8-1ea647ab3f1d.jpg)

**Comment by noobying** [comment]
This is an inherent defect of Mask R-CNN. This werid edge of mask is due to the low resolution of mask generation(28x28). This is friendly to small object. However, fo the big object, this is serious. Because the final mask is Interpolation from the raw mask(28x28), the mask get corase edge. BTW, you can try the SOLO v2(1/4 scale ratio) or Condinst to try the high resolution instance segmentation.  Good lack.

**Comment by kczarnota** [comment]
Thanks for the quick reply, I will follow your advice and try another network.
