### ISSUE TITLE
Detection only shows aeroplane and bicycle

### ISSUE THREAD

**Issue by Soodep** [open-mmlab/mmdetection#5716]
I am testing KITTI dataset with : python tools/test.py configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py checkpoints/faster_rcnn_r50_fpn_1x_voc0712_20200624-c9895d40.pth --show
I just want to see result for two classes: car and person. So I modified the number of classes=2 in config file and also changes classes to only classes = ( car, person) in voc.py. But the result I am getting is very unexpected: it shows bicycle and aeroplane bounding boxes everywhere in the image. Please any one suggest what I am doing wrong

<img width="587" alt="file" src="https://user-images.githubusercontent.com/9031472/127415580-bd72a742-ad2a-40f9-a948-aee6728b181b.PNG">

**Comment by noobying** [comment]
Hello, In the test phase, the `classes` you modified in the config will be overwriten in the https://github.com/open-mmlab/mmdetection/blob/c13db2b062ed1d7c0bb8b9134b9a1158c6d30f24/tools/test.py#L195. So this will explain the apperance of `bicycle` and `aeroplane`.
Next, you get the horrible visualization reuslts is due to you change the model parmamter when testing, e.g. the `fc layer` used to classify the categories is initial in the test phase due to mismatching with the training paramter. Here is my reproduce in the `MS COCO`. I also modify the `class:80->2`, `classes:{'person', 'car'}` in `coco.py`.
![image](https://user-images.githubusercontent.com/42159793/127459575-321f5ef6-c48e-4220-96af-9ecb222ad2f6.png)
![image](https://user-images.githubusercontent.com/42159793/127459616-320912ce-dc4d-4a05-aa3a-1218ea7cbb8f.png)

How to solve?
If you just want to observe the model performance on spefic classes, you can just reach to [GUI](https://mmdetection.readthedocs.io/en/latest/useful_tools.html#visualize-predictions) for help and no need to modify the config and any module in `mmdet`. Hope to help you :)

**Comment by Soodep** [comment]
> Hello, In the test phase, the `classes` you modified in the config will be overwriten in the
> 
> https://github.com/open-mmlab/mmdetection/blob/c13db2b062ed1d7c0bb8b9134b9a1158c6d30f24/tools/test.py#L195
> 
> . So this will explain the apperance of `bicycle` and `aeroplane`.
> Next, you get the horrible visualization reuslts is due to you change the model parmamter when testing, e.g. the `fc layer` used to classify the categories is initial in the test phase due to mismatching with the training paramter. Here is my reproduce in the `MS COCO`. I also modify the `class:80->2`, `classes:{'person', 'car'}` in `coco.py`.
> ![image](https://user-images.githubusercontent.com/42159793/127459575-321f5ef6-c48e-4220-96af-9ecb222ad2f6.png)
> ![image](https://user-images.githubusercontent.com/42159793/127459616-320912ce-dc4d-4a05-aa3a-1218ea7cbb8f.png)
> How to solve?
> If you just want to observe the model performance on spefic classes, you can just reach to [GUI](https://mmdetection.readthedocs.io/en/latest/useful_tools.html#visualize-predictions) for help and no need to modify the config and any module in `mmdet`. [Demo here](https://www.youtube.com/watch?v=4imQyECTik0). Hope to help you :)

Thank you very much noobying. I really appreciate your help. I used the GUI tool like you suggested and ran: python DetVisGUI_test.py configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py checkpoints/faster_rcnn_r50_fpn_1x_voc0712_20200624-c9895d40.pth data/VOCdevkit/VOC2012/JPEGImages/ --device cuda
But I am again getting unusual result as follows:

<img width="604" alt="dfd" src="https://user-images.githubusercontent.com/9031472/127536835-6acc30d2-7b13-41b5-9d19-767b92452b78.PNG">

**Comment by noobying** [comment]
No worries! You should follow this to check it out. Good luck.
![image](https://user-images.githubusercontent.com/42159793/127577683-a4bccbcf-3e34-4e21-baec-809b036e49d6.png)

**Comment by Soodep** [comment]
Dear noobying sorry for too many stupid question, but after using this  i am getting this error.
<img width="345" alt="fddfdfdf" src="https://user-images.githubusercontent.com/9031472/127583620-2a1b845d-1b76-4bce-a651-90c945b853fc.PNG">

**Comment by noobying** [comment]
Sorry for that. I didn't meet this before. Maybe you can check your data format, etc.

**Comment by Soodep** [comment]
> > Dear noobying sorry for too many stupid question, but after using this i am getting this error.
> > <img alt="fddfdfdf" width="345" src="https://user-images.githubusercontent.com/9031472/127583620-2a1b845d-1b76-4bce-a651-90c945b853fc.PNG">
> 
> The value of "xmin" is a string ('577.41'), so it cannot be converted to int.

How do I solve this issue?

**Comment by RangiLyu** [comment]
> > > Dear noobying sorry for too many stupid question, but after using this i am getting this error.
> > > <img alt="fddfdfdf" width="345" src="https://user-images.githubusercontent.com/9031472/127583620-2a1b845d-1b76-4bce-a651-90c945b853fc.PNG">
> > 
> > 
> > The value of "xmin" is a string ('577.41'), so it cannot be converted to int.
> 
> How do I solve this issue?

'577.41' is a string of float, so just convert it to float first.
