### ISSUE TITLE
Why octave_base_scale=4 in Retina_Head?

### ISSUE THREAD

**Issue by DuCheng2018** [open-mmlab/mmdetection#603]
In my opinion, octave_base_scale=1 is more sensible.
If octave_base_scale=4, anchor_scales will be 4x2^(1/3) and 4x2^(2/3).
It looks so weird.

**Comment by hellock** [comment]
We follow the official implementation of RetinaNet.

**Comment by cassie101** [comment]
Hi @hellock, I have a question and would be thankful if you can help answer as you are very familiar with object detection. 
In RetinaNet, C3 which stride=8, has anchor of scale 32, 32*(2**1/3) and 32*(2**2/3). The author didn't explicit mention, but what do you think is the intuition of starting with 32? i.e. What is the intuition of having 4 times the anchor stride? 
Thank you very much if you can share your experience.

**Comment by alexwq100** [comment]
Hi @hellock, I have a question and would be thankful if you can help answer as you are very familiar with object detection.
In RetinaNet, C3 which stride=8, has anchor of scale 32, 32*(2**1/3) and 32*(2**2/3). The author didn't explicit mention, but what do you think is the intuition of starting with 32 instead of say 16 or 8? i.e. What is the intuition of having 4 times the anchor stride?
Thank you very much if you can share your experience.


add+1

**Comment by ottolu** [comment]
@DuCheng2018 it's related to the input image size. I think it's more likely to be an empiric setting, maybe based on some hyperparameter searching.
