### ISSUE TITLE
FocalLoss with OhemSampler gives error

### ISSUE THREAD

**Issue by victoryc** [open-mmlab/mmdetection#6129]
When I try to use FocalLoss together with OhemSampler, I get the following error:
```
		ohem_sampler.py", line 48, in hard_mining
		    _, topk_loss_inds = loss.topk(num_expected)
		RuntimeError: invalid argument 5: k not in range for dimension at /pytorch/aten/src/THC/generic/THCTensorTopK.cu:26
```

Any idea about the cause/fix? Though combining OHEM with Focal Loss won't be a common option, I don't see them as really mutually exclusive.

Thanks.

**Comment by ZwwWayne** [comment]
This usually requires returning the loss without reduction. It seems that the classification loss has been averaged and summed up. OHEM sampler should not work with FocalLoss because the weight of each item has already been calculated with the factored defined in FocalLoss, thus the return of FocalLoss is already a scalar that cannot work with OHEM.
