### ISSUE TITLE
problem about "show_result(..., out_file)"?

### ISSUE THREAD

**Issue by Peterisfar** [open-mmlab/mmdetection#613]
![image](https://user-images.githubusercontent.com/31852119/57433229-87aef200-726a-11e9-8937-49e6f3604ae5.png)

when i use out_file to save result , but there is no imgs saved , where is the error?

**Comment by HuangQinJian** [comment]
> ![image](https://user-images.githubusercontent.com/31852119/57433229-87aef200-726a-11e9-8937-49e6f3604ae5.png)
> 
> when i use out_file to save result , but there is no imgs saved , where is the error?

me too!

**Comment by zhijl** [comment]
Here's a pull request #403 that was about this problem before, but recently I also found the way still didn't work. Here's a workable way to solve the problem by finding where the problem lies [mmdet/apis/inference.py#L77-L83](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/inference.py#L77-L83) and explicitly pass in the parameter `out_file`, at least so that the image file named `out_file` can be generated normally.
Details:
lines from 77 to 83 in `mmdet/apis/inference.py`
``` py
    mmcv.imshow_det_bboxes(
        img.copy(),
        bboxes,
        labels,
        class_names=class_names,
        score_thr=score_thr,
        show=out_file is None)
```
Change into ->
``` py
    mmcv.imshow_det_bboxes(
        img.copy(),
        bboxes,
        labels,
        class_names=class_names,
        score_thr=score_thr,
        show=out_file is None,
        out_file=out_file)
```
and then update locally installed mmdetection by `pip install -e .` under the root path of mmdetection. Try again, it will work.
I'm not sure if there‘s such a feature in Python grammar that function `imshow_det_bboxes` recognized  the variable `out_file` in `out_file is None` as a parameter of the same name when `out_file is None` showed in the parameter list. The Python version I used is 3.6.8, at least not supported at all, and maybe it's really a mmdetection BUG. @hellock

**Comment by hellock** [comment]
@zhijl Thanks for your help! This is a bug of #403. Would you create a PR to fix it?

**Comment by Peterisfar** [comment]
> Here's a pull request #403 that was about this problem before, but recently I also found the way still didn't work. Here's a workable way to solve the problem by finding where the problem lies [mmdet/apis/inference.py#L77-L83](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/inference.py#L77-L83) and explicitly pass in the parameter `out_file`, at least so that the image file named `out_file` can be generated normally.
> Details:
> lines from 77 to 83 in `mmdet/apis/inference.py`
> 
> ```python
>     mmcv.imshow_det_bboxes(
>         img.copy(),
>         bboxes,
>         labels,
>         class_names=class_names,
>         score_thr=score_thr,
>         show=out_file is None)
> ```
> 
> Change into ->
> 
> ```python
>     mmcv.imshow_det_bboxes(
>         img.copy(),
>         bboxes,
>         labels,
>         class_names=class_names,
>         score_thr=score_thr,
>         show=out_file is None,
>         out_file=out_file)
> ```
> 
> and then update locally installed mmdetection by `pip install -e .` under the root path of mmdetection. Try again, it will work.
> I'm not sure if there‘s such a feature in Python grammar that function `imshow_det_bboxes` recognized the variable `out_file` in `out_file is None` as a parameter of the same name when `out_file is None` showed in the parameter list. The Python version I used is 3.6.8, at least not supported at all, and maybe it's really a mmdetection BUG. @hellock

thanks

**Comment by zhijl** [comment]
> @zhijl Thanks for your help! This is a bug of #403. Would you create a PR to fix it?

Got it, I've created pull request #630
