### ISSUE TITLE
How to use mixup and mosaic augmentation

### ISSUE THREAD

**Issue by Brym-Gyimah** [open-mmlab/mmdetection#6155]
I have been trying to implement mosaic and mixup augmentation but always get stuck with these errors. I dont know how to navigate it through, hoping for some help.
Thank you

Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/mmdetection/mmdet/datasets/custom.py", line 195, in __getitem__
    data = self.prepare_train_img(idx)
  File "/content/mmdetection/mmdet/datasets/custom.py", line 218, in prepare_train_img
    return self.pipeline(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 2255, in __call__
    results = self._mixup_transform(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 2286, in _mixup_transform
    assert 'mix_results' in results
AssertionError

**Comment by hhaAndroid** [comment]
@Brym-Gyimah mosaic and mixup must be used together with MultiImageMixDataset.

**Comment by Brym-Gyimah** [comment]
Is there an example of how MultiImageMixDataset has been used as I’m not getting much clarity on the official doc

**Comment by junhuplim** [comment]
You can take a look at the yolox model config, it uses MultiImageMixDataset there

**Comment by y78h11b09** [comment]
Hi, did you solve it?  I added the content referencing to the yolox model config,  I thus  have the same problem. I found that it happen at the second epochs, it is difference between  the loading train_pipelines. but I don't know how to fix it.

**Comment by junnnxie** [comment]
hi, I met the same problem with you.but it is about mosaic_transform, do you solve it? really need your help,thx.

**Comment by junhuplim** [comment]
@y78h11b09 sorry for the late response, have not been following the thread. Have you managed to solve it?

@junnnxie have you tried the aforementioned yolox config? If you did, can I know more about the error message?

**Comment by junnnxie** [comment]
> @y78h11b09 sorry for the late response, have not been following the thread. Have you managed to solve it?
> 
> @junnnxie have you tried the aforementioned yolox config? If you did, can I know more about the error message?

![image](https://user-images.githubusercontent.com/63383988/139669193-554fd92c-2b83-45ed-aba6-8835e5b7c65a.png)
about the yolox config I just modify the dataset path and num_classes.my dataset has 9 classes with different resolution like 1024x1024, 1536x1536.

**Comment by junhuplim** [comment]
Can you also show your config file? thanks

**Comment by junnnxie** [comment]
> Can you also show your config file? thanks

_base_ = ['./schedules/schedule_1x.py', './default_runtime.py']

# model settings
model = dict(
    type='YOLOX',
    backbone=dict(type='CSPDarknet', deepen_factor=0.33, widen_factor=0.5),
    neck=dict(
        type='YOLOXPAFPN',
        in_channels=[128, 256, 512],
        out_channels=128,
        num_csp_blocks=1),
    bbox_head=dict(
        type='YOLOXHead', num_classes=9, in_channels=128, feat_channels=128),
    train_cfg=dict(assigner=dict(type='SimOTAAssigner', center_radius=2.5)),
    # In order to align the source code, the threshold of the val phase is
    # 0.01, and the threshold of the test phase is 0.001.
    test_cfg=dict(score_thr=0.01, nms=dict(type='nms', iou_threshold=0.65)))

# dataset settings
data_root = 'nfs/project/netdisk/192.168.10.223/object_detection/project/merge/'
dataset_type = 'CocoDataset'

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

img_scale = (1024, 1024)

train_pipeline = [
    dict(type='Mosaic', img_scale=img_scale, pad_val=114.0),
    dict(
        type='RandomAffine',
        scaling_ratio_range=(0.1, 2),
        border=(-img_scale[0] // 2, -img_scale[1] // 2)),
    dict(
        type='MixUp',
        img_scale=img_scale,
        ratio_range=(0.8, 1.6),
        pad_val=114.0),
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Resize', keep_ratio=True),
    dict(type='Pad', pad_to_square=True, pad_val=114.0),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]

train_dataset = dict(
    type='MultiImageMixDataset',
    dataset=dict(
        type=dataset_type,
        ann_file=data_root + 'json/train.json',
        img_prefix=data_root + 'images/all/',
        pipeline=[
            dict(type='LoadImageFromFile', to_float32=True),
            dict(type='LoadAnnotations', with_bbox=True)
        ],
        filter_empty_gt=False,
    ),
    pipeline=train_pipeline,
    dynamic_scale=img_scale)

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_scale,
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Pad', size=img_scale, pad_val=114.0),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]

data = dict(
    samples_per_gpu=4,#8,
    workers_per_gpu=2,
    train=train_dataset,
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'json/val.json',
        img_prefix=data_root + 'images/val/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'json/val.json',
        img_prefix=data_root + 'images/val/',
        pipeline=test_pipeline))

# optimizer
# default 8 gpu
optimizer = dict(
    type='SGD',
    lr=0.01,
    momentum=0.9,
    weight_decay=5e-4,
    nesterov=True,
    paramwise_cfg=dict(norm_decay_mult=0., bias_decay_mult=0.))
optimizer_config = dict(grad_clip=None)

# learning policy
lr_config = dict(
    _delete_=True,
    policy='YOLOX',
    warmup='exp',
    by_epoch=False,
    warmup_by_epoch=True,
    warmup_ratio=1,
    warmup_iters=5,  # 5 epoch
    num_last_epochs=15,
    min_lr_ratio=0.05)
runner = dict(type='EpochBasedRunner', max_epochs=300)

resume_from = None
interval = 10

custom_hooks = [
    dict(type='YOLOXModeSwitchHook', num_last_epochs=15, priority=48),
    dict(
        type='SyncRandomSizeHook',
        ratio_range=(14, 26),
        img_scale=img_scale,
        priority=48),
    dict(
        type='SyncNormHook',
        num_last_epochs=15,
        interval=interval,
        priority=48),
    dict(type='ExpMomentumEMAHook', resume_from=resume_from, priority=49)
]
checkpoint_config = dict(interval=interval)
evaluation = dict(interval=interval, metric='bbox')
log_config = dict(interval=50)

**Comment by junnnxie** [comment]
> Can you also show your config file? thanks

I can train other networks like cascade_rcnn with no problem, I think the yolox config still need to modify but I have no idea.

**Comment by junnnxie** [comment]
> I have been trying to implement mosaic and mixup augmentation but always get stuck with these errors. I dont know how to navigate it through, hoping for some help. Thank you
> 
> Caught AssertionError in DataLoader worker process 0. Original Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop data = fetcher.fetch(index) File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/content/mmdetection/mmdet/datasets/custom.py", line 195, in **getitem** data = self.prepare_train_img(idx) File "/content/mmdetection/mmdet/datasets/custom.py", line 218, in prepare_train_img return self.pipeline(results) File "/content/mmdetection/mmdet/datasets/pipelines/compose.py", line 41, in **call** data = t(data) File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 2255, in **call** results = self._mixup_transform(results) File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 2286, in _mixup_transform assert 'mix_results' in results AssertionError

hi, do you solve your problem?I also met it and didin't work it out. hope to  have your help

**Comment by y78h11b09** [comment]
you can do "workflow = [('train', 24 ),('val',1)]",  and commented  runner = dict(type = 'EpochBasedRunner', max_epoches=50), other configs  as following the yolox configs:

# Model
conv_cfg = dict(type='ConvDWS')
norm_cfg = dict(type='SyncBN',momentum=0.01, eps=1e-3)#dict(type='SyncBN'),
act_cfg = dict(type='Mish') #'Mish' 'MemoryEfficientSwish','Swish'(),

model = dict(
type='CPSS',
backbone=dict(
),
neck=dict(
),
bbox_head=dict(
),
)
#training and testing settings
train_cfg = dict(
assigner=dict(type='CPSSAssigner', topk=9, match_lost_gt=False,lamda=1),
allowed_border=-1,
pos_weight=-1,
debug=False,#,
frozenset=dict(fronzed_layers= None, excluded_layers=None) #
)

test_cfg = dict(
nms_pre=1000,
min_bbox_size=0,
score_thr=0.05,#default 0.05
nms=dict(type='soft_nms', iou_threshold=0.60, min_score=0.05),#default:0.6

max_per_img=100)


dataset_type = 'CrowdHumanDataset'
# dataset_type = 'CocoDataset'
data_root = '/home/yangxb/mmdetection-master/data/crowdhuman/'

img_size = (896, 896)

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    to_rgb=True)

train_pipeline = [

  dict(type='Mosaic', img_scale=img_size, pad_val=114.0),
dict(
type='RandomAffine',
scaling_ratio_range=(0.1, 2),
border=(-img_size[0] // 2, -img_size[1] // 2)
),
dict(type='MixUp', img_scale=img_size, ratio_range=(0.8, 1.6), pad_val=114.0),
dict(type='PhotoMetricDistortion',
brightness_delta=32,
contrast_range=(0.5, 1.5),
saturation_range=(0.5, 1.5),
hue_delta=18),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Resize', keep_ratio=True),
dict(type='Pad', pad_to_square=True, pad_val=114.0),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_size,
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Pad', size=img_size, pad_val=114.0),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]

data = dict(
samples_per_gpu = 2,# imgs_per_gpu=8,#[2,4,8]
workers_per_gpu=0,#[0,1,2]
train=dict(
type='MultiImageMixDataset',
dataset=dict(
type=dataset_type,
ann_file=data_root + 'annotations/train.json',
img_prefix=data_root + 'CrowdHuman_train/Images/',
pipeline=[dict(type='LoadImageFromFile', to_float32=True),
                     dict(type='LoadAnnotations', with_bbox=True)],
            filter_empty_gt=False,
),
        pipeline=train_pipeline,
dynamic_scale= img_size
),
val=dict(
type=dataset_type,
ann_file=data_root + 'annotations/val.json',
img_prefix=data_root + 'CrowdHuman_val/Images/',
pipeline=test_pipeline
),
test=dict(
type=dataset_type,
ann_file=data_root + 'annotations/val.json',
img_prefix=data_root + 'CrowdHuman_val/Images/',
pipeline=test_pipeline,
# test_mode =True
),
)



 optimizer = dict(
     type='SGD',
     lr=2e-4,#default 0.01 for 8gpus,bs 64
     momentum=0.9,
     weight_decay=5e-4,
     nesterov=True,
     paramwise_cfg=dict(norm_decay_mult=0., bias_decay_mult=0.))

optimizer_config = dict(grad_clip=dict(max_norm=35.0, norm_type=2))
lr_config = dict(
# policy='cosine',
# target_lr=1e-4,
policy='CosineAnnealing',
    # lr_warmup_init = 0.008,
    # lr_warmup_epoch=1.0,
min_lr = 1e-8,
min_lr_ratio=None,
by_epoch=False,
warmup='linear',
warmup_iters=917,
warmup_ratio=1.0/3
)


evaluation = dict(interval=1, metric='bbox')
checkpoint_config = dict(interval=1)

# yapf:disable
log_config = dict(
interval=300,#300,100,50
hooks=[
dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')#visualize
])
# yapf:enable
# runtime settings
total_epochs =12
device_ids = range(2)#oringal

dist_params = dict(backend = 'nccl')
log_level = 'INFO'
work_dir = '/home/yangxb/crowdhuman/'
load_from = '/home/yangxb/crowdhuman/epoch_10.pth'

resume_from =  None


# #
interval = 10
#
custom_hooks = [
    dict(type='YOLOXModeSwitchHook', num_last_epochs=5, priority=48),#default num_last_epochs=15
    dict(
        type='SyncRandomSizeHook',
        ratio_range=(12, 13),#default 24,26
        img_scale=img_size,#img_scale
        priority=48),
    dict(
        type='SyncNormHook',
        num_last_epochs=5,#default num_last_epochs=15
        interval=interval,
        priority=48),
    dict(type='ExpMomentumEMAHook', resume_from=resume_from, priority=49)
]

# runner = dict(type='EpochBasedRunner', max_epochs=50)
workflow =[('train',24),('val',1)]



which yet happens  the error of 'max_results' in results,  but it can run all the epoch and don't effect the validate 


***@***.***
 
From: junnnxie
Date: 2021-11-01 22:01
To: open-mmlab/mmdetection
CC: y78h11b09; Mention
Subject: Re: [open-mmlab/mmdetection] How to use mixup and mosaic augmentation (#6155)
I have been trying to implement mosaic and mixup augmentation but always get stuck with these errors. I dont know how to navigate it through, hoping for some help. Thank you
Caught AssertionError in DataLoader worker process 0. Original Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop data = fetcher.fetch(index) File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/content/mmdetection/mmdet/datasets/custom.py", line 195, in getitem data = self.prepare_train_img(idx) File "/content/mmdetection/mmdet/datasets/custom.py", line 218, in prepare_train_img return self.pipeline(results) File "/content/mmdetection/mmdet/datasets/pipelines/compose.py", line 41, in call data = t(data) File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 2255, in call results = self._mixup_transform(results) File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 2286, in _mixup_transform assert 'mix_results' in results AssertionError
hi, do you solve your problem?I also met it and didin't work it out. hope to have your help
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by junnnxie** [comment]
> you can do "workflow = [('train', 24 ),('val',1)]", and commented runner = dict(type = 'EpochBasedRunner', max_epoches=50), other configs as following the yolox configs: # Model conv_cfg = dict(type='ConvDWS') norm_cfg = dict(type='SyncBN',momentum=0.01, eps=1e-3)#dict(type='SyncBN'), act_cfg = dict(type='Mish') #'Mish' 'MemoryEfficientSwish','Swish'(), model = dict( type='CPSS', backbone=dict( ), neck=dict( ), bbox_head=dict( ), ) #training and testing settings train_cfg = dict( assigner=dict(type='CPSSAssigner', topk=9, match_lost_gt=False,lamda=1), allowed_border=-1, pos_weight=-1, debug=False,#, frozenset=dict(fronzed_layers= None, excluded_layers=None) # ) test_cfg = dict( nms_pre=1000, min_bbox_size=0, score_thr=0.05,#default 0.05 nms=dict(type='soft_nms', iou_threshold=0.60, min_score=0.05),#default:0.6 max_per_img=100) dataset_type = 'CrowdHumanDataset' # dataset_type = 'CocoDataset' data_root = '/home/yangxb/mmdetection-master/data/crowdhuman/' img_size = (896, 896) img_norm_cfg = dict( mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True) train_pipeline = [ dict(type='Mosaic', img_scale=img_size, pad_val=114.0), dict( type='RandomAffine', scaling_ratio_range=(0.1, 2), border=(-img_size[0] // 2, -img_size[1] // 2) ), dict(type='MixUp', img_scale=img_size, ratio_range=(0.8, 1.6), pad_val=114.0), dict(type='PhotoMetricDistortion', brightness_delta=32, contrast_range=(0.5, 1.5), saturation_range=(0.5, 1.5), hue_delta=18), dict(type='RandomFlip', flip_ratio=0.5), dict(type='Resize', keep_ratio=True), dict(type='Pad', pad_to_square=True, pad_val=114.0), dict(type='Normalize', **img_norm_cfg), dict(type='DefaultFormatBundle'), dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']), ] test_pipeline = [ dict(type='LoadImageFromFile'), dict( type='MultiScaleFlipAug', img_scale=img_size, flip=False, transforms=[ dict(type='Resize', keep_ratio=True), dict(type='RandomFlip'), dict(type='Pad', size=img_size, pad_val=114.0), dict(type='Normalize', **img_norm_cfg), dict(type='DefaultFormatBundle'), dict(type='Collect', keys=['img']) ]) ] data = dict( samples_per_gpu = 2,# imgs_per_gpu=8,#[2,4,8] workers_per_gpu=0,#[0,1,2] train=dict( type='MultiImageMixDataset', dataset=dict( type=dataset_type, ann_file=data_root + 'annotations/train.json', img_prefix=data_root + 'CrowdHuman_train/Images/', pipeline=[dict(type='LoadImageFromFile', to_float32=True), dict(type='LoadAnnotations', with_bbox=True)], filter_empty_gt=False, ), pipeline=train_pipeline, dynamic_scale= img_size ), val=dict( type=dataset_type, ann_file=data_root + 'annotations/val.json', img_prefix=data_root + 'CrowdHuman_val/Images/', pipeline=test_pipeline ), test=dict( type=dataset_type, ann_file=data_root + 'annotations/val.json', img_prefix=data_root + 'CrowdHuman_val/Images/', pipeline=test_pipeline, # test_mode =True ), ) optimizer = dict( type='SGD', lr=2e-4,#default 0.01 for 8gpus,bs 64 momentum=0.9, weight_decay=5e-4, nesterov=True, paramwise_cfg=dict(norm_decay_mult=0., bias_decay_mult=0.)) optimizer_config = dict(grad_clip=dict(max_norm=35.0, norm_type=2)) lr_config = dict( # policy='cosine', # target_lr=1e-4, policy='CosineAnnealing', # lr_warmup_init = 0.008, # lr_warmup_epoch=1.0, min_lr = 1e-8, min_lr_ratio=None, by_epoch=False, warmup='linear', warmup_iters=917, warmup_ratio=1.0/3 ) evaluation = dict(interval=1, metric='bbox') checkpoint_config = dict(interval=1) # yapf:disable log_config = dict( interval=300,#300,100,50 hooks=[ dict(type='TextLoggerHook'), # dict(type='TensorboardLoggerHook')#visualize ]) # yapf:enable # runtime settings total_epochs =12 device_ids = range(2)#oringal dist_params = dict(backend = 'nccl') log_level = 'INFO' work_dir = '/home/yangxb/crowdhuman/' load_from = '/home/yangxb/crowdhuman/epoch_10.pth' resume_from = None # # interval = 10 # custom_hooks = [ dict(type='YOLOXModeSwitchHook', num_last_epochs=5, priority=48),#default num_last_epochs=15 dict( type='SyncRandomSizeHook', ratio_range=(12, 13),#default 24,26 img_scale=img_size,#img_scale priority=48), dict( type='SyncNormHook', num_last_epochs=5,#default num_last_epochs=15 interval=interval, priority=48), dict(type='ExpMomentumEMAHook', resume_from=resume_from, priority=49) ] # runner = dict(type='EpochBasedRunner', max_epochs=50) workflow =[('train',24),('val',1)] which yet happens the error of 'max_results' in results, but it can run all the epoch and don't effect the validate ***@***.*** From: junnnxie Date: 2021-11-01 22:01 To: open-mmlab/mmdetection CC: y78h11b09; Mention Subject: Re: [open-mmlab/mmdetection] How to use mixup and mosaic augmentation (#6155) I have been trying to implement mosaic and mixup augmentation but always get stuck with these errors. I dont know how to navigate it through, hoping for some help. Thank you Caught AssertionError in DataLoader worker process 0. Original Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop data = fetcher.fetch(index) File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/content/mmdetection/mmdet/datasets/custom.py", line 195, in getitem data = self.prepare_train_img(idx) File "/content/mmdetection/mmdet/datasets/custom.py", line 218, in prepare_train_img return self.pipeline(results) File "/content/mmdetection/mmdet/datasets/pipelines/compose.py", line 41, in call data = t(data) File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 2255, in call results = self._mixup_transform(results) File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 2286, in _mixup_transform assert 'mix_results' in results AssertionError hi, do you solve your problem?I also met it and didin't work it out. hope to have your help — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

hi, I tried your ways but I found it didn't save the checkpoint file after training several epoches. seems the checkpoint file will save after validation.

**Comment by y78h11b09** [comment]
It can save  the checkpoint file and validate. both of them are not effected by it.

the checkpoint is saved first and then to be validate in my envoriment pytorch 1.4 and mmdection (1.1+ , not 2.0+)



***@***.***
 
From: junnnxie
Date: 2021-11-02 16:09
To: open-mmlab/mmdetection
CC: y78h11b09; Mention
Subject: Re: [open-mmlab/mmdetection] How to use mixup and mosaic augmentation (#6155)
you can do "workflow = [('train', 24 ),('val',1)]", and commented runner = dict(type = 'EpochBasedRunner', max_epoches=50), other configs as following the yolox configs: # Model conv_cfg = dict(type='ConvDWS') norm_cfg = dict(type='SyncBN',momentum=0.01, eps=1e-3)#dict(type='SyncBN'), act_cfg = dict(type='Mish') #'Mish' 'MemoryEfficientSwish','Swish'(), model = dict( type='CPSS', backbone=dict( ), neck=dict( ), bbox_head=dict( ), ) #training and testing settings train_cfg = dict( assigner=dict(type='CPSSAssigner', topk=9, match_lost_gt=False,lamda=1), allowed_border=-1, pos_weight=-1, debug=False,#, frozenset=dict(fronzed_layers= None, excluded_layers=None) # ) test_cfg = dict( nms_pre=1000, min_bbox_size=0, score_thr=0.05,#default 0.05 nms=dict(type='soft_nms', iou_threshold=0.60, min_score=0.05),#default:0.6 max_per_img=100) dataset_type = 'CrowdHumanDataset' # dataset_type = 'CocoDataset' data_root = '/home/yangxb/mmdetection-master/data/crowdhuman/' img_size = (896, 896) img_norm_cfg = dict( mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True) train_pipeline = [ dict(type='Mosaic', img_scale=img_size, pad_val=114.0), dict( type='RandomAffine', scaling_ratio_range=(0.1, 2), border=(-img_size[0] // 2, -img_size[1] // 2) ), dict(type='MixUp', img_scale=img_size, ratio_range=(0.8, 1.6), pad_val=114.0), dict(type='PhotoMetricDistortion', brightness_delta=32, contrast_range=(0.5, 1.5), saturation_range=(0.5, 1.5), hue_delta=18), dict(type='RandomFlip', flip_ratio=0.5), dict(type='Resize', keep_ratio=True), dict(type='Pad', pad_to_square=True, pad_val=114.0), dict(type='Normalize', *img_norm_cfg), dict(type='DefaultFormatBundle'), dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']), ] test_pipeline = [ dict(type='LoadImageFromFile'), dict( type='MultiScaleFlipAug', img_scale=img_size, flip=False, transforms=[ dict(type='Resize', keep_ratio=True), dict(type='RandomFlip'), dict(type='Pad', size=img_size, pad_val=114.0), dict(type='Normalize', img_norm_cfg), dict(type='DefaultFormatBundle'), dict(type='Collect', keys=['img']) ]) ] data = dict( samples_per_gpu = 2,# imgs_per_gpu=8,#[2,4,8] workers_per_gpu=0,#[0,1,2] train=dict( type='MultiImageMixDataset', dataset=dict( type=dataset_type, ann_file=data_root + 'annotations/train.json', img_prefix=data_root + 'CrowdHuman_train/Images/', pipeline=[dict(type='LoadImageFromFile', to_float32=True), dict(type='LoadAnnotations', with_bbox=True)], filter_empty_gt=False, ), pipeline=train_pipeline, dynamic_scale= img_size ), val=dict( type=dataset_type, ann_file=data_root + 'annotations/val.json', img_prefix=data_root + 'CrowdHuman_val/Images/', pipeline=test_pipeline ), test=dict( type=dataset_type, ann_file=data_root + 'annotations/val.json', img_prefix=data_root + 'CrowdHuman_val/Images/', pipeline=test_pipeline, # test_mode =True ), ) optimizer = dict( type='SGD', lr=2e-4,#default 0.01 for 8gpus,bs 64 momentum=0.9, weight_decay=5e-4, nesterov=True, paramwise_cfg=dict(norm_decay_mult=0., bias_decay_mult=0.)) optimizer_config = dict(grad_clip=dict(max_norm=35.0, norm_type=2)) lr_config = dict( # policy='cosine', # target_lr=1e-4, policy='CosineAnnealing', # lr_warmup_init = 0.008, # lr_warmup_epoch=1.0, min_lr = 1e-8, min_lr_ratio=None, by_epoch=False, warmup='linear', warmup_iters=917, warmup_ratio=1.0/3 ) evaluation = dict(interval=1, metric='bbox') checkpoint_config = dict(interval=1) # yapf:disable log_config = dict( interval=300,#300,100,50 hooks=[ dict(type='TextLoggerHook'), # dict(type='TensorboardLoggerHook')#visualize ]) # yapf:enable # runtime settings total_epochs =12 device_ids = range(2)#oringal dist_params = dict(backend = 'nccl') log_level = 'INFO' work_dir = '/home/yangxb/crowdhuman/' load_from = '/home/yangxb/crowdhuman/epoch_10.pth' resume_from = None # # interval = 10 # custom_hooks = [ dict(type='YOLOXModeSwitchHook', num_last_epochs=5, priority=48),#default num_last_epochs=15 dict( type='SyncRandomSizeHook', ratio_range=(12, 13),#default 24,26 img_scale=img_size,#img_scale priority=48), dict( type='SyncNormHook', num_last_epochs=5,#default num_last_epochs=15 interval=interval, priority=48), dict(type='ExpMomentumEMAHook', resume_from=resume_from, priority=49) ] # runner = dict(type='EpochBasedRunner', max_epochs=50) workflow =[('train',24),('val',1)] which yet happens the error of 'max_results' in results, but it can run all the epoch and don't effect the validate @. From: junnnxie Date: 2021-11-01 22:01 To: open-mmlab/mmdetection CC: y78h11b09; Mention Subject: Re: [open-mmlab/mmdetection] How to use mixup and mosaic augmentation (#6155) I have been trying to implement mosaic and mixup augmentation but always get stuck with these errors. I dont know how to navigate it through, hoping for some help. Thank you Caught AssertionError in DataLoader worker process 0. Original Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop data = fetcher.fetch(index) File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/content/mmdetection/mmdet/datasets/custom.py", line 195, in getitem data = self.prepare_train_img(idx) File "/content/mmdetection/mmdet/datasets/custom.py", line 218, in prepare_train_img return self.pipeline(results) File "/content/mmdetection/mmdet/datasets/pipelines/compose.py", line 41, in call data = t(data) File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 2255, in call results = self._mixup_transform(results) File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 2286, in _mixup_transform assert 'mix_results' in results AssertionError hi, do you solve your problem?I also met it and didin't work it out. hope to have your help — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
hi, I tried your ways but I found it didn't save the checkpoint file after training several epoches. seems the checkpoint file will save after validation.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heartInsert** [comment]
I have  used    Mosaic with  MultiImageMixDataset ,but  I still get  this  bug .

**Comment by wwcc1107** [comment]
I have used Mosaic with MultiImageMixDataset ,but I still get this bug .have you solve this problem

**Comment by Audrey528** [comment]
@hhaAndroid When use `workflow = [('train', 1), ('val', 1)]`， How do I use Mosaic with MultiImageMixDataset. I have the same question, can you help me？ Thanks very much.
