### ISSUE TITLE
where should auto_fp16() be added?

### ISSUE THREAD

**Issue by LeoCho1learning** [open-mmlab/mmdetection#6197]
I found that auto_fp16() was added at detectors/base.py and some necks and was not be added at backbones and heads. so i'm confused about where i should put  auto_fp16().

thank you

**Comment by hhaAndroid** [comment]
@LeoCho1learning The user does not need to add this decorator anywhere because it has already been added in the base class. The presence of this decorator in the neck should be a historical issue, it is actually not needed. you can find in this https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py#L156

**Comment by LeoCho1learning** [comment]
> @LeoCho1learning The user does not need to add this decorator anywhere because it has already been added in the base class. The presence of this decorator in the neck should be a historical issue, it is actually not needed. you can find in this https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py#L156

Thanks for your reply. i also want to know where i should add (self.fp16_enabled = False). I found it at base.py ,some head and some neck. does neck need this line or not?

**Comment by AronLin** [comment]
>  does neck need this line or not?
Yes, you can also find it in `FPN`.

**Comment by hhaAndroid** [comment]
@LeoCho1learning `self.fp16_enabled = False` only needs to be added to the head, the rest is not needed.
