### ISSUE TITLE
Is it possble to convert mmdetection trained model in .pth to .pt for AWS deployment?

### ISSUE THREAD

**Issue by apanand14** [open-mmlab/mmdetection#6346]

**Comment by BIGWangYuDong** [comment]
Can you provide a copy of your current code and let me try it

**Comment by Wangjunkun** [comment]
I met the same problem these days. Have you solved that yet? I tried to rewrite the "forward" function (./mmdet/models/detectors/base.py) but I think its not a good way to achieve. Since the model is based on nn.Module, I am sure that the model can be traced (e.g. torch.jit.trace). Thank you in advance.

**Comment by BIGWangYuDong** [comment]
Feel free to create a new issue if you still meet problems
