### ISSUE TITLE
WandB validation logging error

### ISSUE THREAD

**Issue by sw-jang** [open-mmlab/mmdetection#7000]
Anyone dealt with `wandb: WARNING Step must only increase in log calls`.  issue?

Everything else but validation step is being correctly logged to wandb.

`wandb: WARNING Step must only increase in log calls.  Step 1000 < 1001; dropping {'val/AP50': 0.308, 'val/mAP': 0.308135986328125, 'learning_rate': 0.001, 'momentum': 0.9}.`

Warning above is shown after every validation and nothing is logged.

environments:
- pytorch: 1.10.1
- cuda: 11.3
- mmcv: 1.4.2
- mmdetection: 2.20.0

**Comment by morganmcg1** [comment]
@sw-jang can you share some code to reproduce it? The above error happens when you pass a step number for a step that has already been logged.

If you are logging in multiple places in your code and want all of those calls to be part of the same step, then you can use the `commit-False` argument in `wandb.log`, which won't increment the wandb step count until `wandb.log` is called again elsewhere as normal.

See the [docs here](https://docs.wandb.ai/guides/track/log#stepwise-and-incremental-logging)

If I was to guess what is happening in your situation is that the training data for `step=1000` is being logged (and committed) to wandb, and then the validation data at the 1000th step is also trying to be logged with `step=1000` - but this wandb step count can't receive new data.

**Comment by sw-jang** [comment]
@morganmcg1 
Thank you!

Adding `commit=False` argument when calling `WandbLoggerHook` solved the problem.

**Comment by ug-kim** [comment]
@sw-jang Where do I have to add `commit=False`? Could you see your config which added `WandbLoggerHook`?
