### ISSUE TITLE
Support `IterBasedRunner` for the runner of YOLOX

### ISSUE THREAD

**Issue by Tim-Hung** [open-mmlab/mmdetection#7317]
Thanks for your contribution and we appreciate it a lot.

Just a simple question about training **YOLOX** model.

I'm trying to use semi-supervised learning for **YOLOX**. Therefore, I prefer to use `IterBasedRunner` as most of people do.

However, I found that there are some tricks(`YOLOXModeSwitchHook `or `SyncNormHook`) used in **YOLOX** which is written based on `EpochBasedRunner`.

Is there any convenient way to use these tricks(`YOLOXModeSwitchHook `or `SyncNormHook`) based on `IterBasedRunner`?

Thanks for your help!

**Comment by BIGWangYuDong** [comment]
Hi, sorry for the late response. Seems that these Hook can only be used based on EpochBasedRunner. If you would like to use these hooks, maybe you need to write a hook and set `before_train_iter` function to set switch the model. Because the IterBaseRunner only processes before or after epoch function once during training.

**Comment by Tim-Hung** [comment]
Ok, thanks for your response!

I will try to write the hook for IterBasedRunner.

Thank you!
