### ISSUE TITLE
What should I put for `context` parameter in OHEMSampler?

### ISSUE THREAD

**Issue by yxchng** [open-mmlab/mmdetection#751]
Unlike other samplers, OHEM requires a `context` parameter. What should I fill for this parameter?

I am trying to use it for SSD.

**Comment by yhcao6** [comment]
Currently `OHEM` is only tested on two stage detectors and cascade rcnn, `context` is usually passed by detector itself since in sampling phase it needs submodules of detector like `roi extractor` and `bbox head`.  You can ref to this line https://github.com/open-mmlab/mmdetection/blob/9df04d541927b2acd1b90c018da0ecd35c05530c/mmdet/models/detectors/two_stage.py#L122

SSD implements `hard negative mining` by itself at this line. https://github.com/open-mmlab/mmdetection/blob/9df04d541927b2acd1b90c018da0ecd35c05530c/mmdet/models/anchor_heads/ssd_head.py#L121
You can implements `OHEM` by yourself. It is not too hard.
