### ISSUE TITLE
How to use DyHead with two-stage detector?

### ISSUE THREAD

**Issue by sh1ng** [open-mmlab/mmdetection#7539]
![Screenshot 2022-03-26 at 12-24-50 2106 08322 pdf](https://user-images.githubusercontent.com/2821871/160237248-2faed97a-6b93-4c5b-9c62-eb37dd163cef.png)
It seems you only have a config for one-stage detector.

**Comment by shinya7y** [comment]
Duplicate https://github.com/open-mmlab/mmdetection/issues/7287

**Comment by sh1ng** [comment]
> Duplicate #7287

I'm going to reproduce mask-rcnn with dyhean. I'm using the same config you have mentioned, but it doesn't repeat _c_ from the screen.

**Comment by shinya7y** [comment]
> it doesn't repeat *c* from the screen.

What does this sentence mean?

**Comment by sh1ng** [comment]
Mentioned config is belong to `(b)` configuration from the screen, I'm asking about `(c)`.

**Comment by shinya7y** [comment]
As written in https://github.com/open-mmlab/mmdetection/issues/7287
> The code is based on the official implementation, which is different from Figure 2 (c) of the DyHead paper.

Reproducing the results for Figure 2 (c) will be much harder because only the authors know the implementation details needed to reproduce the paper version.

In my opinion, the implementation of Figure 2 (c) design is low priority.
- The design of Figure 2 (c) is not necessary, considering the AP of Faster R-CNN+DyHead (paper: 38.9, official implementation: 40.3).
- The design of Figure 2 (c) has less usability. We need to change codes other than neck.
