### ISSUE TITLE
when i use analyze_logs.py, i met a error

### ISSUE THREAD

**Issue by hatecodes** [open-mmlab/mmdetection#7661]
hello, when i use
python tools/analysis_tools/analyze_logs.py plot_curve tools/train_all/20220330_092043.log.json --keys  bbox_mAP_50,

i met a error:
raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (300,) and (44,)

[20220330_092043.log.zip](https://github.com/open-mmlab/mmdetection/files/8447764/20220330_092043.log.zip)
this is my json file.  thx for help!!!

**Comment by BIGWangYuDong** [comment]
I have already check your error.
because your log file did not save every epoch log,(only 44 epoches exists in your log file). but it is default to load every epoch. So the shapes are not match.
![sidZd4tejk](https://user-images.githubusercontent.com/48282753/162376034-c25b1d50-2f4f-4e32-b0f6-d6c059b095b7.png)
If you want to fix this error, you need try to change `xs` in your code

**Comment by hatecodes** [comment]
> I have already check your error. because your log file did not save every epoch log,(only 44 epoches exists in your log file). but it is default to load every epoch. So the shapes are not match. ![sidZd4tejk](https://user-images.githubusercontent.com/48282753/162376034-c25b1d50-2f4f-4e32-b0f6-d6c059b095b7.png) If you want to fix this error, you need try to change `xs` in your code

thx bro, i have fixed it ~~~
