### ISSUE TITLE
Resnet Strikes Back Pretrained Models

### ISSUE THREAD

**Issue by smcs88** [open-mmlab/mmdetection#7678]
Hello, are there other models such as Resnet 101 in mmlab? Or can I directly use the models from here:  https://github.com/rwightman/pytorch-image-models/releases/tag/v0.1-rsb-weights

**Comment by chhluo** [comment]
We use checkpoints of backbone provided by mmclassification, and ResNet 101 is not supported yet in mmclassification. The pretained model provided in timm may can not be used directly, because the name of weights in checkpoint of r101 provided by timm may be different from the naming conventions resnet101 in mmdet. You can try to replace the name of weights, and load them.
