### ISSUE TITLE
how can i get （score_thr < num） picture, it is only higher than score_thr pic

### ISSUE THREAD

**Issue by ae86pjh** [open-mmlab/mmdetection#7711]

**Comment by ae86pjh** [comment]
how can i get （score_thr < num） picture, it is only higher than score_thr pic

**Comment by jbwang1997** [comment]
You can change the code [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/post_processing/bbox_nms.py#L55) to filter out objects whose score greater than score_thr. 

But, I don't recommend drawing the lower score objects without the minimum score threshold. Because the low score predictions are too many to draw in the picture.

**Comment by ae86pjh** [comment]
Maybe I can set a range to reduce the images to see which bboxes are still a bit short of the required accuracy.
Anyway, thank you very much!
