### ISSUE TITLE
The instance is divided in the same color

### ISSUE THREAD

**Issue by 15032390092** [open-mmlab/mmdetection#7722]
When I use mask RCNN for instance segmentation, the colors of the masks of the same class of targets in the test results are not distinguished. How can I make the same class have different colors?

**Comment by RangiLyu** [comment]
You can modify this function and implement a random color schema
https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/core/visualization/image.py#L164

**Comment by 15032390092** [comment]
> 

I modified the random color. It only displays different colors for different types of objects, but the colors are the same for different instances of the same type of objects. However, the displayed results do not identify instance 1 and instance 2 For example: person 1 and person 2

**Comment by 15032390092** [comment]
Shouldn't instance segmentation mask RCNN be the result of this?
![image](https://user-images.githubusercontent.com/59554319/163508493-bf1c50fb-21b8-4316-bde5-56bae5aa9e01.png)

**Comment by yellowjs0304** [comment]
@15032390092 I agree with your opinion, did you find the way?

**Comment by neverstoplearn** [comment]
> Shouldn't instance segmentation mask RCNN be the result of this? ![image](https://user-images.githubusercontent.com/59554319/163508493-bf1c50fb-21b8-4316-bde5-56bae5aa9e01.png)

have you solve the question? i meet the same same question.

**Comment by yellowjs0304** [comment]
@neverstoplearn I think it can be help for you.
I wanted to make the random color in same class(In my case, class is only 1)

So, I modified the function in "[image.imshow_det_bboxes](https://github.com/open-mmlab/mmdetection/blob/29e1650bdcd6b5bcc6347c6e04233ef85c31c0b5/mmdet/core/visualization/image.py#L322)", and make the below image.
![image](https://user-images.githubusercontent.com/30281608/207745140-94b86c46-3499-4b40-b591-bb356bec77f3.png)

I used the bbox_color as random color flag, instead of specific color.

```
if segms is not None:
    mask_palette = get_palette(mask_color, max_label + 1)
    if bbox_color == "one_class_random":
        colors = [random.choice(mask_palette) for label in labels[:num_bboxes]]
        # colors = colors
    else:
        colors = [mask_palette[label] for label in labels]
    colors = np.array(colors, dtype=np.uint8)
    draw_masks(ax, img, segms, colors, with_edge=True, alpha = 0.5)
```

**Comment by WenZhitao** [comment]
I meet the same problem, have you solved it yet?
