### ISSUE TITLE
Why swin transformer support multi size training in mmdetection？

### ISSUE THREAD

**Issue by fire717** [open-mmlab/mmdetection#7800]
As I know, swin transformer must fix size in 224 or 384, but in mmdetection when use swin as backbone, it seems can run in very large size, so I wonder how it works.
Thx！

**Comment by chhluo** [comment]
Swin transformer fix size in 224 or 384 for imagenet, (1333, 1000) or (1024, 1024) are common sizes for object detection. swin transformer do self-attention in non-overlapped windows (local area self attention) instead of in whole feature map (global area self attention). And also it do 3 times dowasample to reduce the size of the feature map. Please refer to the paper for detial.

**Comment by fire717** [comment]
OK, When I have time I will dive into the paper and the source code, thanks for your replying!
