### ISSUE TITLE
`to_rgb` is called twice in centernet

### ISSUE THREAD

**Issue by LinkHS** [open-mmlab/mmdetection#7824]
centernet的配置文件"configs/centernet/centernet_resnet18_dcnv2_140e_coco.py"中调用了两次`to_rgb`

1. `RandomCenterCropPad`
```
dict(
    type='RandomCenterCropPad',
    crop_size=(512, 512),
    ratios=(0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3),
    mean=[0, 0, 0],
    std=[1, 1, 1],
    to_rgb=True,
    test_pad_mode=None),
```

这个配置在"mmdet/datasets/pipelines/transforms.py"中`class RandomCenterCropPad`的`__init__()`中执行：
```
  if to_rgb:
      self.mean = mean[::-1]
      self.std = std[::-1]
```

2. Normalize:
```
dict(type='Normalize', ..., to_rgb=True,),
```

最终在"mmcv/image/photometric.py"中的`imnormalize_()`中调用：
```
    if to_rgb:
        cv2.cvtColor(img, cv2.COLOR_BGR2RGB, img)  # inplace
    cv2.subtract(img, mean, img)  # inplace
    cv2.multiply(img, stdinv, img)  # inplace
```

调用两次是个bug，而且normalize的`mean`，`stdinv`和rgb通道也匹配不上吧？

**Comment by hhaAndroid** [comment]
@LinkHS Only the norm value is changed in `RandomCenterCropPad`, the img does not change the channel.  The implementation of `centernet` is based on the Pipeline of [cornernet](https://github.com/open-mmlab/mmdetection/blob/master/configs/cornernet/cornernet_hourglass104_mstest_10x5_210e_coco.py#L50). Since mean is 0 and std is 1, there is no effect on `centernet` accuracy， but this is indeed a bug.  Can you create a PR to fix it ? Thank you
