### ISSUE TITLE
maskrcnn focal loss

### ISSUE THREAD

**Issue by Morizhaoyang** [open-mmlab/mmdetection#7920]
Mask rcnn , how to use focal loss in RPN Head and RCNN Head

**Comment by BIGWangYuDong** [comment]
You can refer to https://github.com/open-mmlab/mmdetection/blob/73b4e65a6a30435ef6a35f405e3474a4d9cfb234/configs/_base_/models/retinanet_r50_fpn.py#L37-L42

**Comment by BIGWangYuDong** [comment]
Focal loss is conflict with rpn sampling, due to its definition. Warning code is as follow:
https://github.com/open-mmlab/mmdetection/blob/73b4e65a6a30435ef6a35f405e3474a4d9cfb234/mmdet/models/dense_heads/anchor_head.py#L84-L99
did you trained your model in coco?
I haven't tried to use focal loss in Faster R-CNN before. but maybe you can add grad_clip or set a smaller learning rate to have another try

**Comment by BIGWangYuDong** [comment]
Also, P2 level will generate lots of anchors, you can try to use P3+
