### ISSUE TITLE
Validation Loss During Training 

### ISSUE THREAD

**Issue by David-Biggs** [open-mmlab/mmdetection#7971]
Getting the validation loss during training seems to be a common issue:
#7871 
#171
#271
#5694
#1093

The most common 'solution' is to set workflow = [('train', 1), ('val', 1)]. 
However, in all the above mentioned issues the same error occurs i.e.,:

 -> TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes' and 'gt_labels' .

I have not been able to find an actual solution. 

Does anyone have any pointers?

Thanks again for the awesome repo!

**Comment by RangiLyu** [comment]
Can you provide more details such as the config you using and the command you run?

**Comment by David-Biggs** [comment]
Hi @RangiLyu 

- The config I am using is - htc_without_semantic_r50_fpn_1x_coco.py. I am aiming to fine-tune the model on my custom COCO dataset. Here is the full config [config.txt](https://github.com/open-mmlab/mmdetection/files/8684441/config.txt)
- I have workflow = [('train', 1), ('val', 1)]
- I am using train_detector() 
- For the datasets argument in train_detector() I set datasets = [build_dataset(cfg.data.train), build_dataset(cfg.data.val)].
- I run the below commands to build the datasets and model and to begin training

![image](https://user-images.githubusercontent.com/64862726/168219465-641f1bbc-e0a6-4613-a283-3bb86aba54fb.png)


Thanks for your help!

**Comment by khalidcawl** [comment]
Hi. Any update on this? I received the same error when trying to get the validation loss.

**Comment by David-Biggs** [comment]
I have not heard from @RangiLyu since the first response. 

The issue label is still ' awaiting response'. Maybe what's why it is not being answered? Is it possible for non-members to change issue labels?

**Comment by khalidcawl** [comment]
Maybe @hellock can shed some light on this? Would be much appreciated.

**Comment by lukas-plojhar** [comment]
Your validation dataset does not return `gt_boxes` and `gt_labels` keys, only `img`.

You need to load the annotations in your validation dataset pipeline (`cfg.data.val.pipeline.transforms`) first:

1) Load annotations by `dict(type='LoadAnnotations', with_bbox=True)` after `dict(type='LoadImageFromFile')`

And then return the additional keys when returning a sample from the dataset:

2) Replace `dict(type='ImageToTensor', keys=['img'])` with `dict(type='DefaultFormatBundle')`

3) Change keys from `dict(type='Collect', keys=['img'])` to `dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])`.

See `cfg.data.train` in your config for reference.

**Comment by David-Biggs** [comment]
Hi @lukas-plojhar 
Thanks so much for your comment. I tried it out as soon as I could. I must have been making a mistake somewhere as I kept getting an error. 

However, I did some more digging and found a solution that worked. I think it does something very similar you your comment. The solution is below:

  1. Add val to work flow -> ` cfg.workflow = [('train', 1), ('val', 1)] `
  2. Edit val pipeline to be a copy of train.pipline. Add val data set to datasets: 
  `datasets = [build_dataset(cfg.data.train)] `
  `if len(cfg.workflow) == 2:`
  `          `       ` val_dataset = copy.deepcopy(cfg.data.val)`
     ` `     `val_dataset.pipeline = cfg.data.train.pipeline`
      ` `   ` datasets.append(build_dataset(val_dataset))`

When I train, I now get a printout of val mAP and val loss.

**Comment by lukas-plojhar** [comment]
Hey @David-Biggs, glad you worked it out. Just be careful when copying `cfg.data.train.pipeline` to `val_dataset.pipeline` , because you also copy all training data augmentations.

Validation pipeline should be **invariant**. If validation pipeline outputs slightly different samples due to data augmentation (flipping, cropping, etc.) every time. So if you do 10 same validation runs in a row, each will vary because model is being fed different validation samples every run and mAP will change because of data augmentations and not because of your model improving. You should always validate on the exact same samples to see how your model is improving.

**Comment by David-Biggs** [comment]
Hi @lukas-plojhar, thanks for the heads-up. 
So if I am understanding you correctly, these two statements are essentially the same. 

  1) Follow the steps in your first comment
  2)  Copy `cfg.data.train.pipeline` to `val_dataset.pipline`  while pre


`            dict(
               `` type='MultiScaleFlipAug',
               `` img_scale=(1333, 800),
                ``flip=False,
                ``transforms=[
                  ````  dict(type='Resize', keep_ratio=True),
                  ````  dict(type='RandomFlip'),
                  ````  dict(
                    ``````    type='Normalize',
                    ``````    mean=[123.675, 116.28, 103.53],
                   ``````     std=[58.395, 57.12, 57.375],
                    ``````    to_rgb=True),
                  ````  dict(type='Pad', size_divisor=32),`

**Comment by lukas-plojhar** [comment]
@David-Biggs I am not 100% sure on this one, but it should be the same in this case. However, if you were to use more augmentations in your train pipeline, then it could become malicious when used in valid pipeline. 

What I proposed in my solution is, that you edit only the beginning and the end of the valid pipeline to load and return annotations, respectively. 

What you propose is also correct **in this particular situation** as you have no data augmentations besides MultiScaleFlipAug ( https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/test_time_aug.py), sometimes it's used in train pipeline ) in the pipeline, which only resize the sample. If you were to have let's say horizontal flip with a 0.5 probability (and you see it often in the default configs), and you were to copy paste this **whole** train pipeline to the valid pipeline, then your validation dataset would not be invariant, because there is a 50 % possibility of outputting a different sample. Do you know where I am going with this? You need to make sure, that your validation dataset is always the same so it can objectively track your model's performance.

**Comment by lukas-plojhar** [comment]
Apparently, there are contrary opinions: https://stats.stackexchange.com/questions/320800/data-augmentation-on-training-set-only/320967#320967 

It might be **safer to disregard my comments on data augmentatoins in validation pipeline**. However, personally I follow the described logic of not augmenting the validation pipeline. 

I am just a student writing my Master's thesis and I do not have the appropriate knowledge to make such claims with certainty. Maybe some else will shed some light on that.

**Comment by David-Biggs** [comment]
Hi @lukas-plojhar, thanks for that StackExchange link. 

I am of the opinion that the validation set can be seen as the target for the model,  one would 'aim' the model towards the validation set (fine-tune its HPs to perform well on the validation set). The test set is used to test how well the model performs on a similar unseen target. (I hope this analogy makes sense ). Therefore I think it would not be fair to apply augmentations during validation while not applying augmentation during testing and _visa versa_. As long as the augmentations have no random aspects. Otherwise, as you stated, the validation dataset would not be invariant. 


But I could be mistaken and if anyone disagrees it would be great for this discussion to continue. It seems that MMDetection by default has in some models a RandomFlip transform in their test pipelines. Which opposed my augment.  

I am also a student writing my master's thesis.

@lukas-plojhar are you the Lukasz Grad who comments in the StackExchange questions linked? 

Thanks a lot for your help!

**Comment by lukas-plojhar** [comment]
@David-Biggs 
I see where you going with that and I think it reflects the point made in the previous StackExchange link; if you train with augmentations, you should feed the model the input it was trained on, i.e. augmented input. 

Yes, I have noticed RandomFlip is necessary in some pipelines and can't be run without, but I don't know why.  

No, I am not that Lukazs guy, and best of luck with your thesis :-)

**Comment by abdksyed** [comment]
I am trying the same, but getting an error.
`KeyError: 'ann_info' ` after the first epoch on train_dataset is done. I have searched, and I think the answer is because some flag `test_mode` needs to be kept `False` when adding `val` to `workflow`. By default, for `val_dataset`, the `test_mode` is `True`, But I need help finding the flag/tag, any idea where is it in the config?

**Comment by abdksyed** [comment]
> Hi @lukas-plojhar Thanks so much for your comment. I tried it out as soon as I could. I must have been making a mistake somewhere as I kept getting an error.
> 
> However, I did some more digging and found a solution that worked. I think it does something very similar you your comment. The solution is below:
> 
> 1. Add val to work flow -> `cfg.workflow = [('train', 1), ('val', 1)]`
> 2. Edit val.pipeline to be a copy of train.pipline. Add val data set to datasets:
>    `datasets = [build_dataset(cfg.data.train)] `
>    `if len(cfg.workflow) == 2:`
>    `          `       ` val_dataset = copy.deepcopy(cfg.data.val)`
>    ` `     `val_dataset.pipeline = cfg.data.train.pipeline`
>    ` `   ` datasets.append(build_dataset(val_dataset))`
> 
> When I train, I now get a printout of val mAP and val loss.

Also which file does this code change needs to be done?

I am trying to do this on notebook, without editing the library code, is it possible to do it? Or else we need to do the library code change for it to be working?

**Comment by hyq12358** [comment]
How to get val loss in mmdetection3.x?

**Comment by GiTilemac** [comment]
Is there any update on this issue?
