### ISSUE TITLE
How to export torchScript model ？

### ISSUE THREAD

**Issue by zhangleigood** [open-mmlab/mmdetection#8272]

**Comment by Czm369** [comment]
You can try MMDeploy
https://github.com/open-mmlab/mmdeploy

**Comment by GeorgePearse** [comment]
Hey @Czm369 it's very difficult to then separate the torchscript model from MMDeploy. Is it the same for the other formats, e.g. TensorRT ? 

Would it include all of the required preprocessing to work?

**Comment by Daniil-Osokin** [comment]
Hi! You can switch to `torchscript` instead of `onnx` in deploy config file: from `'../_base_/backends/onnxruntime.py'` to `'../_base_/backends/torchscript.py'`, and from `_base_ = ['../_base_/torchscript_config.py']` to `_base_ = ['../_base_/torchscript_config.py']` in task config file. Then `tools/deploy.py` from MMDeploy will save traced model.
