### ISSUE TITLE
How to train mask2former and scnet with my custom dataset

### ISSUE THREAD

**Issue by yeonsikch** [open-mmlab/mmdetection#8431]
Hi.
I'm training mask rcnn for instance segmentation.
And training went well.

Go further,  I wanna train mask2former and scnet for instance segmentation with my custom dataset(num of cls = 1).

## Quesetion 1.
Should I receive stuff or panoptic dataset and learn it together?
(I know how to receive them and I recevied them.)
my custom dataset is only segmentation annotations and image.

## Question 2.
How to make config for data?

Thank u for ur time and see.
I've been struggling with this for several days. :(

**Comment by chhluo** [comment]
Question 1: I suggest that convertef you dataset to coco format, refer to https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html.

Question 2: For instance segmentation, num_stuff must be 0, and num_thing = 1 due to (num of cls =1).

Best practice: copy https://github.com/open-mmlab/mmdetection/blob/master/configs/mask2former/mask2former_r50_lsj_8x2_50e_coco.py and modify num_thing  and settings for dataset (don't forget to add classes=('class1', )).
