### ISSUE TITLE
Using mmdetection to separate images

### ISSUE THREAD

**Issue by gabrielalexandre** [open-mmlab/mmdetection#8548]
Hello, I'm new to the area and I'm studying mmdetection, I trained a code that recognizes different types of things (cars, motorcycles, people, animals among others). I would like to know if there is a possibility to assemble a code that uses this AI that I trained so that I separate images into different folders, for example, one just for cars, others just for people, doing so for all the objects that my code recognizes .

**Comment by RangiLyu** [comment]
Of course. You can use the trained model to recognize the objects the images, and then write a script to parse the detection results, so that you can separate images. 
You can follow the guide about how to inference an image with a trained model: https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html#inference-with-existing-models
And here is a notebook demo:
https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb
