### ISSUE TITLE
How to use mmsegmentation from mmdetection?

### ISSUE THREAD

**Issue by susaha** [open-mmlab/mmdetection#8650]
I want to use some of the mmsegmentation modules from mmdetection, e.g., an encoder or backbone for semantic segmentation.
Please let me know if there is a way to do that following mmdetection doc.

**Comment by muhd-umer** [comment]
I would assume it would be along the lines of how ConvNeXt was implemented in MMDetection, i.e., you add the following custom import to your config; 
```python
cfg.custom_imports = dict(imports=['mmcls.models'], allow_failed_imports=False)
```
Since you want to import from `mmseg`, that is what you will use in place of `mmcls`. Then, you can use your choice of, say, a backbone by modifying the model architecture in your config.
```python
cfg.model.backbone=dict(
    type='mmseg.BACKBONE',   # Where BACBBONE should be a class implemented in MMSeg
    ...
)
...
```
This is how I've been using custom imports from other OpenMM Libraries, and may or may not be the right way to do so. I hope one of the contributors can clarify or provide a better way.

**Comment by susaha** [comment]
@muhd-umer: thanks for the explanation and sharing the script. Much appreciated!
