### ISSUE TITLE
Questions about RTMDet-Tiny and RTMDet-Small models. 

### ISSUE THREAD

**Issue by cydiachen** [open-mmlab/mmdetection#8888]
Thanks for your excellent job! 
I am now trying to reimplement your network. After carefully exploration on config files, I found an interesting differences between small models ( such as Tiny and Small Model). These models have different bbox_head compared with larger model ( M, L, XL), whose `exp_on_reg` is set to False. 
I am now wondering why do you choose to disable exp_on_reg on small models?

**Comment by RangiLyu** [comment]
Actually, there is no performance difference in whether adding exp on the regression. It's just because the M, L, and X are trained in July. The legacy version of the code has exp but we planed to remove it. 

In the beginning, according to the schedule, we plan to retrain the model before release. 
But due to the cluster failure, our training processes were killed and couldn't catch up with the release. Thus, we had to use the weights trained from a few months ago.

I'm very sorry that this caused you trouble, we will update the retrained model in a later version.

**Comment by cydiachen** [comment]
> Actually, there is no performance difference in whether adding exp on the regression. It's just because the M, L, and X are trained in July. The legacy version of the code has exp but we planed to remove it.
> 
> In the beginning, according to the schedule, we plan to retrain the model before release. But due to the cluster failure, our training processes were killed and couldn't catch up with the release. Thus, we had to use the weights trained from a few months ago.
> 
> I'm very sorry that this caused you trouble, we will update the retrained model in a later version.

Thx a lot. Just a little curious about the differences. Thank you for your excellent job.
