### ISSUE TITLE
Load checkpoint to GPU but still exist in CPU

### ISSUE THREAD

**Issue by manhtd98** [open-mmlab/mmdetection#9052]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

I loaded the checkpoint to GPU. 
But with my config still, 4GB model exist in CPU. 

### Environment

pytorch 1.9

**Comment by zachcoleman** [comment]
This is due to the NVIDIA driver overhead caused by the first call of `cuda` in PyTorch.

Here's an example of a really tiny tensor before being moved to GPU:
![Screen Shot 2022-10-17 at 10 40 37 AM](https://user-images.githubusercontent.com/42484306/196234726-c88dcb3d-ecd4-4d37-8c99-cf5bc9e93841.png)

Then after being moved to GPU:
![Screen Shot 2022-10-17 at 10 41 18 AM](https://user-images.githubusercontent.com/42484306/196234846-84be07d3-654e-4fa1-be95-ba77f2a7fb37.png)

The NVIDIA drivers use ~4GB of RAM. Here's a discussion here on PyTorch forums about it: https://discuss.pytorch.org/t/cpu-ram-usage-with-cuda-is-large-2-gb/117668

**Comment by manhtd98** [comment]
How can we avoid it or refresh it?

**Comment by zachcoleman** [comment]
If you want to use a CUDA gpu, there is no avoiding this. This is just the price/overhead of using CUDA.

**Comment by Czm369** [comment]
Thanks for your issue and experience sharing !
We have no experience with this at the moment, maybe you can ask MMDeploy, they have more experience with mobile deployment.
