### ISSUE TITLE
Please make a description table for each of the configs key

### ISSUE THREAD

**Issue by raytu** [open-mmlab/mmdetection#926]
Can you please make a description table to help explain what each key does in the config file?

**Comment by hellock** [comment]
Since most components are pluggable, we may not describe the keys of each components in the config files. You can find the meaning of each argument in the corresponding modules, e.g., arguments of [ResNet](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnet.py#L334), [HRNet](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/hrnet.py#L196), [SingleRoIExtractor](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_extractors/single_level.py#L12), etc.
Some early modules may not have detailed inline documentation and we will work on that.
