### ISSUE TITLE
soft teacher

### ISSUE THREAD

**Issue by ahomez** [open-mmlab/mmdetection#9596]
### What's the feature?

Hello, I see that you have added the soft teacher model to mmdet3. x, and I wonder if you have ever tried to train soft teacher model based on full coco dataset(coco_train_2017 and coco_unlabeled data). The source code requires 8 gpus to train 720k iters, which is too strict for individual users.

**Comment by Czm369** [comment]
Actually, we don't train soft teacher model based on full coco dataset. Because we found that there exits a large room for hyperparameters optimization and we are doing some researsh on the semi-supervised object detection.  In the near future, we will provide a general semi-supervised object detection framework that is suitable for most detection models and provide some high-precision semi-supervised pre-training models for users to download.
